// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AuthorizeRequest {
    /// The X.509 certificated presented by EV and encoded in PEM format.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub certificate: Option<heapless::String<5500usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken,
    #[cfg_attr(feature = "serde", serde(rename = "iso15118CertificateHashData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub iso15118_certificate_hash_data: Option<heapless::Vec<OCSPRequestData, 4usize>>,
}
#[cfg(feature = "alloc")]
impl crate::Action for AuthorizeRequest {
    const ACTION: &'static str = "Authorize";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AuthorizeRequest<const ID_TOKEN_ADDITIONAL_INFO_CAP: usize = 16usize> {
    /// The X.509 certificated presented by EV and encoded in PEM format.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub certificate: Option<heapless::String<5500usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken<ID_TOKEN_ADDITIONAL_INFO_CAP>,
    #[cfg_attr(feature = "serde", serde(rename = "iso15118CertificateHashData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub iso15118_certificate_hash_data: Option<heapless::Vec<OCSPRequestData, 4usize>>,
}
#[cfg(not(feature = "alloc"))]
impl<const ID_TOKEN_ADDITIONAL_INFO_CAP: usize> crate::Action
for AuthorizeRequest<ID_TOKEN_ADDITIONAL_INFO_CAP> {
    const ACTION: &'static str = "Authorize";
}
