// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearChargingProfileRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfileCriteria"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_profile_criteria: Option<ClearChargingProfile<CustomDataType>>,
    /// The Id of the charging profile to clear.
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfileId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_profile_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
impl<CustomDataType> crate::Action for ClearChargingProfileRequest<CustomDataType> {
    const ACTION: &'static str = "ClearChargingProfile";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for ClearChargingProfileRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.charging_profile_criteria {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("chargingProfileCriteria"))?;
        }
        Ok(())
    }
}
