// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearVariableMonitoringRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// List of the monitors to be cleared, identified by there Id.
    pub id: alloc::vec::Vec<i64>,
}
#[cfg(feature = "alloc")]
impl crate::Action for ClearVariableMonitoringRequest {
    const ACTION: &'static str = "ClearVariableMonitoring";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearVariableMonitoringRequest<
    const CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// List of the monitors to be cleared, identified by there Id.
    pub id: heapless::Vec<i64, CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<const CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP: usize> crate::Action
for ClearVariableMonitoringRequest<CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP> {
    const ACTION: &'static str = "ClearVariableMonitoring";
}
