// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Get15118EVCertificateRequest {
    pub action: CertificateActionEnum,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Raw CertificateInstallationReq request from EV, Base64 encoded.
    #[cfg_attr(feature = "serde", serde(rename = "exiRequest"))]
    pub exi_request: heapless::String<5600usize>,
    /// Schema version currently used for the 15118 session between EV and Charging Station. Needed for parsing of the EXI stream by the CSMS.
    #[cfg_attr(feature = "serde", serde(rename = "iso15118SchemaVersion"))]
    pub iso15118_schema_version: heapless::String<50usize>,
}
impl crate::Action for Get15118EVCertificateRequest {
    const ACTION: &'static str = "Get15118EVCertificate";
}
