// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetTransactionStatusResponse {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Whether there are still message to be delivered.
    #[cfg_attr(feature = "serde", serde(rename = "messagesInQueue"))]
    pub messages_in_queue: bool,
    /// Whether the transaction is still ongoing.
    #[cfg_attr(feature = "serde", serde(rename = "ongoingIndicator"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub ongoing_indicator: Option<bool>,
}
impl crate::Action for GetTransactionStatusResponse {
    const ACTION: &'static str = "GetTransactionStatus";
}
