// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleResponse<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub schedule: Option<CompositeSchedule<CustomDataType>>,
    pub status: GenericStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<StatusInfo<CustomDataType>>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for GetCompositeScheduleResponse<CustomDataType> {
    const ACTION: &'static str = "GetCompositeSchedule";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for GetCompositeScheduleResponse<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.schedule {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("schedule"))?;
        }
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        if let Some(value) = &self.status_info {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("statusInfo"))?;
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleResponse<
    CustomDataType = crate::NoCustomData,
    const COMPOSITE_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub schedule: Option<
        CompositeSchedule<
            CustomDataType,
            COMPOSITE_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
        >,
    >,
    pub status: GenericStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<StatusInfo<CustomDataType>>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const COMPOSITE_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
> crate::Action
for GetCompositeScheduleResponse<
    CustomDataType,
    COMPOSITE_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
> {
    const ACTION: &'static str = "GetCompositeSchedule";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const COMPOSITE_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
> crate::validate::Validate
for GetCompositeScheduleResponse<
    CustomDataType,
    COMPOSITE_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.schedule {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("schedule"))?;
        }
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        if let Some(value) = &self.status_info {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("statusInfo"))?;
        }
        Ok(())
    }
}
