// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InstallCertificateRequest<CustomDataType = crate::NoCustomData> {
    /// A PEM encoded X.509 certificate.
    pub certificate: alloc::string::String,
    #[cfg_attr(feature = "serde", serde(rename = "certificateType"))]
    pub certificate_type: InstallCertificateUseEnum,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for InstallCertificateRequest<CustomDataType> {
    const ACTION: &'static str = "InstallCertificate";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for InstallCertificateRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_max_length(&self.certificate, 5500usize)
            .map_err(|error| error.in_field("certificate"))?;
        crate::validate::Validate::validate(&self.certificate_type)
            .map_err(|error| error.in_field("certificateType"))?;
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InstallCertificateRequest<
    CustomDataType = crate::NoCustomData,
    const INSTALL_CERTIFICATE_REQUEST_CERTIFICATE_CAP: usize = 1024usize,
> {
    /// A PEM encoded X.509 certificate.
    pub certificate: heapless::String<INSTALL_CERTIFICATE_REQUEST_CERTIFICATE_CAP>,
    #[cfg_attr(feature = "serde", serde(rename = "certificateType"))]
    pub certificate_type: InstallCertificateUseEnum,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const INSTALL_CERTIFICATE_REQUEST_CERTIFICATE_CAP: usize,
> crate::Action
for InstallCertificateRequest<
    CustomDataType,
    INSTALL_CERTIFICATE_REQUEST_CERTIFICATE_CAP,
> {
    const ACTION: &'static str = "InstallCertificate";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const INSTALL_CERTIFICATE_REQUEST_CERTIFICATE_CAP: usize,
> crate::validate::Validate
for InstallCertificateRequest<
    CustomDataType,
    INSTALL_CERTIFICATE_REQUEST_CERTIFICATE_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_max_length(&self.certificate, 5500usize)
            .map_err(|error| error.in_field("certificate"))?;
        crate::validate::Validate::validate(&self.certificate_type)
            .map_err(|error| error.in_field("certificateType"))?;
        Ok(())
    }
}
