// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyChargingLimitRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimit"))]
    pub charging_limit: ChargingLimit<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_schedule: Option<alloc::vec::Vec<ChargingSchedule<CustomDataType>>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The charging schedule contained in this notification applies to an EVSE. evseId must be &gt; 0.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyChargingLimitRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyChargingLimit";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for NotifyChargingLimitRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.charging_limit)
            .map_err(|error| error.in_field("chargingLimit"))?;
        if let Some(value) = &self.charging_schedule {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("chargingSchedule"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| {
                        error.in_index(index).in_field("chargingSchedule")
                    })?;
            }
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyChargingLimitRequest<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_CHARGING_LIMIT_REQUEST_CHARGING_SCHEDULE_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimit"))]
    pub charging_limit: ChargingLimit<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_schedule: Option<
        heapless::Vec<
            ChargingSchedule<
                CustomDataType,
                CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
                SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
            >,
            NOTIFY_CHARGING_LIMIT_REQUEST_CHARGING_SCHEDULE_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The charging schedule contained in this notification applies to an EVSE. evseId must be &gt; 0.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_CHARGING_LIMIT_REQUEST_CHARGING_SCHEDULE_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
> crate::Action
for NotifyChargingLimitRequest<
    CustomDataType,
    NOTIFY_CHARGING_LIMIT_REQUEST_CHARGING_SCHEDULE_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
> {
    const ACTION: &'static str = "NotifyChargingLimit";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const NOTIFY_CHARGING_LIMIT_REQUEST_CHARGING_SCHEDULE_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
> crate::validate::Validate
for NotifyChargingLimitRequest<
    CustomDataType,
    NOTIFY_CHARGING_LIMIT_REQUEST_CHARGING_SCHEDULE_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.charging_limit)
            .map_err(|error| error.in_field("chargingLimit"))?;
        if let Some(value) = &self.charging_schedule {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("chargingSchedule"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| {
                        error.in_index(index).in_field("chargingSchedule")
                    })?;
            }
        }
        Ok(())
    }
}
