// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyMonitoringReportRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: alloc::string::String,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitor: Option<alloc::vec::Vec<MonitoringData>>,
    /// The id of the GetMonitoringRequest that requested this report.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl crate::Action for NotifyMonitoringReportRequest {
    const ACTION: &'static str = "NotifyMonitoringReport";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyMonitoringReportRequest<
    const NOTIFY_MONITORING_REPORT_REQUEST_GENERATED_AT_CAP: usize = 1024usize,
    const NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP: usize = 16usize,
    const MONITORING_DATA_VARIABLE_MONITORING_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: heapless::String<
        NOTIFY_MONITORING_REPORT_REQUEST_GENERATED_AT_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitor: Option<
        heapless::Vec<
            MonitoringData<MONITORING_DATA_VARIABLE_MONITORING_CAP>,
            NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP,
        >,
    >,
    /// The id of the GetMonitoringRequest that requested this report.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const NOTIFY_MONITORING_REPORT_REQUEST_GENERATED_AT_CAP: usize,
    const NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP: usize,
    const MONITORING_DATA_VARIABLE_MONITORING_CAP: usize,
> crate::Action
for NotifyMonitoringReportRequest<
    NOTIFY_MONITORING_REPORT_REQUEST_GENERATED_AT_CAP,
    NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP,
    MONITORING_DATA_VARIABLE_MONITORING_CAP,
> {
    const ACTION: &'static str = "NotifyMonitoringReport";
}
