// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PublishFirmwareStatusNotificationRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Required if status is Published. Can be multiple URI’s, if the Local Controller supports e.g. HTTP, HTTPS, and FTP.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub location: Option<alloc::vec::Vec<heapless::String<512usize>>>,
    /// The request id that was
    /// provided in the
    /// PublishFirmwareRequest which
    /// triggered this action.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub request_id: Option<i64>,
    pub status: PublishFirmwareStatusEnum,
}
#[cfg(feature = "alloc")]
impl crate::Action for PublishFirmwareStatusNotificationRequest {
    const ACTION: &'static str = "PublishFirmwareStatusNotification";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PublishFirmwareStatusNotificationRequest<
    const PUBLISH_FIRMWARE_STATUS_NOTIFICATION_REQUEST_LOCATION_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Required if status is Published. Can be multiple URI’s, if the Local Controller supports e.g. HTTP, HTTPS, and FTP.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub location: Option<
        heapless::Vec<
            heapless::String<512usize>,
            PUBLISH_FIRMWARE_STATUS_NOTIFICATION_REQUEST_LOCATION_CAP,
        >,
    >,
    /// The request id that was
    /// provided in the
    /// PublishFirmwareRequest which
    /// triggered this action.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub request_id: Option<i64>,
    pub status: PublishFirmwareStatusEnum,
}
#[cfg(not(feature = "alloc"))]
impl<
    const PUBLISH_FIRMWARE_STATUS_NOTIFICATION_REQUEST_LOCATION_CAP: usize,
> crate::Action
for PublishFirmwareStatusNotificationRequest<
    PUBLISH_FIRMWARE_STATUS_NOTIFICATION_REQUEST_LOCATION_CAP,
> {
    const ACTION: &'static str = "PublishFirmwareStatusNotification";
}
