// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PublishFirmwareRequest<CustomDataType = crate::NoCustomData> {
    /// The MD5 checksum over the entire firmware file as a hexadecimal string of length 32.
    pub checksum: heapless::String<32usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// This contains a string containing a URI pointing to a
    /// location from which to retrieve the firmware.
    pub location: heapless::String<512usize>,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// This specifies how many times Charging Station must try
    /// to download the firmware before giving up. If this field is not
    /// present, it is left to Charging Station to decide how many times it wants to retry.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub retries: Option<i64>,
    /// The interval in seconds
    /// after which a retry may be
    /// attempted. If this field is not
    /// present, it is left to Charging
    /// Station to decide how long to wait
    /// between attempts.
    #[cfg_attr(feature = "serde", serde(rename = "retryInterval"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub retry_interval: Option<i64>,
}
impl<CustomDataType> crate::Action for PublishFirmwareRequest<CustomDataType> {
    const ACTION: &'static str = "PublishFirmware";
}
