// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReportChargingProfilesRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: ChargingLimitSourceEnum,
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: alloc::vec::Vec<ChargingProfile<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The evse to which the charging profile applies. If evseId = 0, the message contains an overall limit for the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Id used to match the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt; message with the resulting ReportChargingProfilesRequest messages. When the CSMS provided a requestId in the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt;, this field SHALL contain the same value.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// To Be Continued. Default value when omitted: false. false indicates that there are no further messages as part of this report.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for ReportChargingProfilesRequest<CustomDataType> {
    const ACTION: &'static str = "ReportChargingProfiles";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReportChargingProfilesRequest<
    CustomDataType = crate::NoCustomData,
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: ChargingLimitSourceEnum,
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: heapless::Vec<
        ChargingProfile<
            CustomDataType,
            CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
            SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
        >,
        REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The evse to which the charging profile applies. If evseId = 0, the message contains an overall limit for the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Id used to match the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt; message with the resulting ReportChargingProfilesRequest messages. When the CSMS provided a requestId in the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt;, this field SHALL contain the same value.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// To Be Continued. Default value when omitted: false. false indicates that there are no further messages as part of this report.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
> crate::Action
for ReportChargingProfilesRequest<
    CustomDataType,
    REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
> {
    const ACTION: &'static str = "ReportChargingProfiles";
}
