// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetNetworkProfileRequest<CustomDataType = crate::NoCustomData> {
    /// Slot in which the configuration should be stored.
    #[cfg_attr(feature = "serde", serde(rename = "configurationSlot"))]
    pub configuration_slot: i64,
    #[cfg_attr(feature = "serde", serde(rename = "connectionData"))]
    pub connection_data: NetworkConnectionProfile<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
impl<CustomDataType> crate::Action for SetNetworkProfileRequest<CustomDataType> {
    const ACTION: &'static str = "SetNetworkProfile";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for SetNetworkProfileRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.connection_data)
            .map_err(|error| error.in_field("connectionData"))?;
        Ok(())
    }
}
