// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetChargingProfileRequest {
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: ChargingProfile,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// For TxDefaultProfile an evseId=0 applies the profile to each individual evse. For ChargingStationMaxProfile and ChargingStationExternalConstraints an evseId=0 contains an overal limit for the whole Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
}
#[cfg(feature = "alloc")]
impl crate::Action for SetChargingProfileRequest {
    const ACTION: &'static str = "SetChargingProfile";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetChargingProfileRequest<
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize = 1024usize,
    const CHARGING_PROFILE_VALID_FROM_CAP: usize = 1024usize,
    const CHARGING_PROFILE_VALID_TO_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: ChargingProfile<
        CHARGING_SCHEDULE_START_SCHEDULE_CAP,
        CHARGING_PROFILE_VALID_FROM_CAP,
        CHARGING_PROFILE_VALID_TO_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// For TxDefaultProfile an evseId=0 applies the profile to each individual evse. For ChargingStationMaxProfile and ChargingStationExternalConstraints an evseId=0 contains an overal limit for the whole Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize,
    const CHARGING_PROFILE_VALID_FROM_CAP: usize,
    const CHARGING_PROFILE_VALID_TO_CAP: usize,
> crate::Action
for SetChargingProfileRequest<
    CHARGING_SCHEDULE_START_SCHEDULE_CAP,
    CHARGING_PROFILE_VALID_FROM_CAP,
    CHARGING_PROFILE_VALID_TO_CAP,
> {
    const ACTION: &'static str = "SetChargingProfile";
}
