// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetMonitoringBaseRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "monitoringBase"))]
    pub monitoring_base: MonitoringBaseEnum,
}
impl crate::Action for SetMonitoringBaseRequest {
    const ACTION: &'static str = "SetMonitoringBase";
}
