// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetVariablesRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "setVariableData"))]
    pub set_variable_data: alloc::vec::Vec<SetVariableData>,
}
#[cfg(feature = "alloc")]
impl crate::Action for SetVariablesRequest {
    const ACTION: &'static str = "SetVariables";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetVariablesRequest<
    const SET_VARIABLES_REQUEST_SET_VARIABLE_DATA_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "setVariableData"))]
    pub set_variable_data: heapless::Vec<
        SetVariableData,
        SET_VARIABLES_REQUEST_SET_VARIABLE_DATA_CAP,
    >,
}
#[cfg(not(feature = "alloc"))]
impl<const SET_VARIABLES_REQUEST_SET_VARIABLE_DATA_CAP: usize> crate::Action
for SetVariablesRequest<SET_VARIABLES_REQUEST_SET_VARIABLE_DATA_CAP> {
    const ACTION: &'static str = "SetVariables";
}
