// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TriggerMessageRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse: Option<EVSE<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "requestedMessage"))]
    pub requested_message: MessageTriggerEnum,
}
impl<CustomDataType> crate::Action for TriggerMessageRequest<CustomDataType> {
    const ACTION: &'static str = "TriggerMessage";
}
