// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BootNotificationResponse {
    #[cfg_attr(feature = "serde", serde(rename = "currentTime"))]
    pub current_time: crate::OcppTimestamp,
    pub interval: i64,
    pub status: BootNotificationResponseStatus,
}
impl crate::Action for BootNotificationResponse {
    const ACTION: &'static str = "BootNotification";
}
