// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CertificateSignedRequest {
    #[cfg_attr(feature = "serde", serde(rename = "certificateChain"))]
    pub certificate_chain: alloc::string::String,
}
#[cfg(feature = "alloc")]
impl crate::Action for CertificateSignedRequest {
    const ACTION: &'static str = "CertificateSigned";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CertificateSignedRequest<
    const CERTIFICATE_SIGNED_REQUEST_CERTIFICATE_CHAIN_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "certificateChain"))]
    pub certificate_chain: heapless::String<
        CERTIFICATE_SIGNED_REQUEST_CERTIFICATE_CHAIN_CAP,
    >,
}
#[cfg(not(feature = "alloc"))]
impl<const CERTIFICATE_SIGNED_REQUEST_CERTIFICATE_CHAIN_CAP: usize> crate::Action
for CertificateSignedRequest<CERTIFICATE_SIGNED_REQUEST_CERTIFICATE_CHAIN_CAP> {
    const ACTION: &'static str = "CertificateSigned";
}
