// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearChargingProfileRequest {
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfilePurpose"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_profile_purpose: Option<ChargingProfilePurpose>,
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "stackLevel"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub stack_level: Option<i64>,
}
impl crate::Action for ClearChargingProfileRequest {
    const ACTION: &'static str = "ClearChargingProfile";
}
