// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DataTransferRequest {
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub data: Option<alloc::string::String>,
    #[cfg_attr(feature = "serde", serde(rename = "messageId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub message_id: Option<heapless::String<50usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vendorId"))]
    pub vendor_id: heapless::String<255usize>,
}
#[cfg(feature = "alloc")]
impl crate::Action for DataTransferRequest {
    const ACTION: &'static str = "DataTransfer";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl crate::validate::Validate for DataTransferRequest {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DataTransferRequest<const DATA_TRANSFER_REQUEST_DATA_CAP: usize = 1024usize> {
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub data: Option<heapless::String<DATA_TRANSFER_REQUEST_DATA_CAP>>,
    #[cfg_attr(feature = "serde", serde(rename = "messageId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub message_id: Option<heapless::String<50usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vendorId"))]
    pub vendor_id: heapless::String<255usize>,
}
#[cfg(not(feature = "alloc"))]
impl<const DATA_TRANSFER_REQUEST_DATA_CAP: usize> crate::Action
for DataTransferRequest<DATA_TRANSFER_REQUEST_DATA_CAP> {
    const ACTION: &'static str = "DataTransfer";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<const DATA_TRANSFER_REQUEST_DATA_CAP: usize> crate::validate::Validate
for DataTransferRequest<DATA_TRANSFER_REQUEST_DATA_CAP> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        Ok(())
    }
}
