// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DataTransferResponse {
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub data: Option<alloc::string::String>,
    pub status: Status,
}
#[cfg(feature = "alloc")]
impl crate::Action for DataTransferResponse {
    const ACTION: &'static str = "DataTransfer";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DataTransferResponse<
    const DATA_TRANSFER_RESPONSE_DATA_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub data: Option<heapless::String<DATA_TRANSFER_RESPONSE_DATA_CAP>>,
    pub status: Status,
}
#[cfg(not(feature = "alloc"))]
impl<const DATA_TRANSFER_RESPONSE_DATA_CAP: usize> crate::Action
for DataTransferResponse<DATA_TRANSFER_RESPONSE_DATA_CAP> {
    const ACTION: &'static str = "DataTransfer";
}
