// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DiagnosticsStatusNotificationRequest {
    pub status: DiagnosticsStatusNotificationRequestStatus,
}
impl crate::Action for DiagnosticsStatusNotificationRequest {
    const ACTION: &'static str = "DiagnosticsStatusNotification";
}
