// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FirmwareStatusNotificationResponse {}
impl crate::Action for FirmwareStatusNotificationResponse {
    const ACTION: &'static str = "FirmwareStatusNotification";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for FirmwareStatusNotificationResponse {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        Ok(())
    }
}
