// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetConfigurationResponse {
    #[cfg_attr(feature = "serde", serde(rename = "configurationKey"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub configuration_key: Option<alloc::vec::Vec<ConfigurationKeyItem>>,
    #[cfg_attr(feature = "serde", serde(rename = "unknownKey"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub unknown_key: Option<alloc::vec::Vec<heapless::String<50usize>>>,
}
#[cfg(feature = "alloc")]
impl crate::Action for GetConfigurationResponse {
    const ACTION: &'static str = "GetConfiguration";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetConfigurationResponse<
    const GET_CONFIGURATION_RESPONSE_CONFIGURATION_KEY_CAP: usize = 16usize,
    const GET_CONFIGURATION_RESPONSE_UNKNOWN_KEY_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "configurationKey"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub configuration_key: Option<
        heapless::Vec<
            ConfigurationKeyItem,
            GET_CONFIGURATION_RESPONSE_CONFIGURATION_KEY_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "unknownKey"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub unknown_key: Option<
        heapless::Vec<
            heapless::String<50usize>,
            GET_CONFIGURATION_RESPONSE_UNKNOWN_KEY_CAP,
        >,
    >,
}
#[cfg(not(feature = "alloc"))]
impl<
    const GET_CONFIGURATION_RESPONSE_CONFIGURATION_KEY_CAP: usize,
    const GET_CONFIGURATION_RESPONSE_UNKNOWN_KEY_CAP: usize,
> crate::Action
for GetConfigurationResponse<
    GET_CONFIGURATION_RESPONSE_CONFIGURATION_KEY_CAP,
    GET_CONFIGURATION_RESPONSE_UNKNOWN_KEY_CAP,
> {
    const ACTION: &'static str = "GetConfiguration";
}
