// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetLogResponse {
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub filename: Option<heapless::String<255usize>>,
    pub status: GetLogResponseStatus,
}
impl crate::Action for GetLogResponse {
    const ACTION: &'static str = "GetLog";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for GetLogResponse {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        Ok(())
    }
}
