// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetLocalListVersionResponse {
    #[cfg_attr(feature = "serde", serde(rename = "listVersion"))]
    pub list_version: i64,
}
impl crate::Action for GetLocalListVersionResponse {
    const ACTION: &'static str = "GetLocalListVersion";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for GetLocalListVersionResponse {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        Ok(())
    }
}
