// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleRequest {
    #[cfg_attr(feature = "serde", serde(rename = "chargingRateUnit"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_rate_unit: Option<ChargingRateUnit>,
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    pub connector_id: i64,
    pub duration: i64,
}
impl crate::Action for GetCompositeScheduleRequest {
    const ACTION: &'static str = "GetCompositeSchedule";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for GetCompositeScheduleRequest {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.charging_rate_unit {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("chargingRateUnit"))?;
        }
        Ok(())
    }
}
