// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetInstalledCertificateIdsRequest {
    #[cfg_attr(feature = "serde", serde(rename = "certificateType"))]
    pub certificate_type: CertificateType,
}
impl crate::Action for GetInstalledCertificateIdsRequest {
    const ACTION: &'static str = "GetInstalledCertificateIds";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for GetInstalledCertificateIdsRequest {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.certificate_type)
            .map_err(|error| error.in_field("certificateType"))?;
        Ok(())
    }
}
