// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleResponse {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_schedule: Option<ChargingSchedule>,
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "scheduleStart"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub schedule_start: Option<crate::OcppTimestamp>,
    pub status: GetCompositeScheduleResponseStatus,
}
#[cfg(feature = "alloc")]
impl crate::Action for GetCompositeScheduleResponse {
    const ACTION: &'static str = "GetCompositeSchedule";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl crate::validate::Validate for GetCompositeScheduleResponse {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.charging_schedule {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("chargingSchedule"))?;
        }
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleResponse<
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_schedule: Option<
        ChargingSchedule<CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP>,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "scheduleStart"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub schedule_start: Option<crate::OcppTimestamp>,
    pub status: GetCompositeScheduleResponseStatus,
}
#[cfg(not(feature = "alloc"))]
impl<const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize> crate::Action
for GetCompositeScheduleResponse<CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP> {
    const ACTION: &'static str = "GetCompositeSchedule";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
> crate::validate::Validate
for GetCompositeScheduleResponse<CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.charging_schedule {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("chargingSchedule"))?;
        }
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        Ok(())
    }
}
