// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleResponse {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_schedule: Option<ChargingSchedule>,
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "scheduleStart"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub schedule_start: Option<alloc::string::String>,
    pub status: Status,
}
#[cfg(feature = "alloc")]
impl crate::Action for GetCompositeScheduleResponse {
    const ACTION: &'static str = "GetCompositeSchedule";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCompositeScheduleResponse<
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 16usize,
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize = 1024usize,
    const GET_COMPOSITE_SCHEDULE_RESPONSE_SCHEDULE_START_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_schedule: Option<
        ChargingSchedule<
            CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
            CHARGING_SCHEDULE_START_SCHEDULE_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "scheduleStart"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub schedule_start: Option<
        heapless::String<GET_COMPOSITE_SCHEDULE_RESPONSE_SCHEDULE_START_CAP>,
    >,
    pub status: Status,
}
#[cfg(not(feature = "alloc"))]
impl<
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize,
    const GET_COMPOSITE_SCHEDULE_RESPONSE_SCHEDULE_START_CAP: usize,
> crate::Action
for GetCompositeScheduleResponse<
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    CHARGING_SCHEDULE_START_SCHEDULE_CAP,
    GET_COMPOSITE_SCHEDULE_RESPONSE_SCHEDULE_START_CAP,
> {
    const ACTION: &'static str = "GetCompositeSchedule";
}
