// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InstallCertificateResponse {
    pub status: InstallCertificateResponseStatus,
}
impl crate::Action for InstallCertificateResponse {
    const ACTION: &'static str = "InstallCertificate";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for InstallCertificateResponse {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        Ok(())
    }
}
