// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MeterValuesRequest {
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    pub connector_id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "meterValue"))]
    pub meter_value: alloc::vec::Vec<MeterValueItem>,
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_id: Option<i64>,
}
#[cfg(feature = "alloc")]
impl crate::Action for MeterValuesRequest {
    const ACTION: &'static str = "MeterValues";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MeterValuesRequest<
    const METER_VALUES_REQUEST_METER_VALUE_CAP: usize = 8usize,
    const METER_VALUE_ITEM_SAMPLED_VALUE_CAP: usize = 8usize,
    const SAMPLED_VALUE_ITEM_VALUE_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    pub connector_id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "meterValue"))]
    pub meter_value: heapless::Vec<
        MeterValueItem<METER_VALUE_ITEM_SAMPLED_VALUE_CAP, SAMPLED_VALUE_ITEM_VALUE_CAP>,
        METER_VALUES_REQUEST_METER_VALUE_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_id: Option<i64>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const METER_VALUES_REQUEST_METER_VALUE_CAP: usize,
    const METER_VALUE_ITEM_SAMPLED_VALUE_CAP: usize,
    const SAMPLED_VALUE_ITEM_VALUE_CAP: usize,
> crate::Action
for MeterValuesRequest<
    METER_VALUES_REQUEST_METER_VALUE_CAP,
    METER_VALUE_ITEM_SAMPLED_VALUE_CAP,
    SAMPLED_VALUE_ITEM_VALUE_CAP,
> {
    const ACTION: &'static str = "MeterValues";
}
