// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SecurityEventNotificationRequest {
    #[cfg_attr(feature = "serde", serde(rename = "techInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tech_info: Option<heapless::String<255usize>>,
    pub timestamp: crate::OcppTimestamp,
    pub r#type: heapless::String<255usize>,
}
impl crate::Action for SecurityEventNotificationRequest {
    const ACTION: &'static str = "SecurityEventNotification";
}
