// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendLocalListResponse {
    pub status: Status,
}
impl crate::Action for SendLocalListResponse {
    const ACTION: &'static str = "SendLocalList";
}
