// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SignCertificateRequest {
    pub csr: alloc::string::String,
}
#[cfg(feature = "alloc")]
impl crate::Action for SignCertificateRequest {
    const ACTION: &'static str = "SignCertificate";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SignCertificateRequest<
    const SIGN_CERTIFICATE_REQUEST_CSR_CAP: usize = 1024usize,
> {
    pub csr: heapless::String<SIGN_CERTIFICATE_REQUEST_CSR_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<const SIGN_CERTIFICATE_REQUEST_CSR_CAP: usize> crate::Action
for SignCertificateRequest<SIGN_CERTIFICATE_REQUEST_CSR_CAP> {
    const ACTION: &'static str = "SignCertificate";
}
