// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct StartTransactionResponse {
    #[cfg_attr(feature = "serde", serde(rename = "idTagInfo"))]
    pub id_tag_info: IdTagInfo,
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    pub transaction_id: i64,
}
impl crate::Action for StartTransactionResponse {
    const ACTION: &'static str = "StartTransaction";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for StartTransactionResponse {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.id_tag_info)
            .map_err(|error| error.in_field("idTagInfo"))?;
        Ok(())
    }
}
