// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct StatusNotificationRequest {
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    pub connector_id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "errorCode"))]
    pub error_code: ErrorCode,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub info: Option<heapless::String<50usize>>,
    pub status: StatusNotificationRequestStatus,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub timestamp: Option<crate::OcppTimestamp>,
    #[cfg_attr(feature = "serde", serde(rename = "vendorErrorCode"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vendor_error_code: Option<heapless::String<50usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vendorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vendor_id: Option<heapless::String<255usize>>,
}
impl crate::Action for StatusNotificationRequest {
    const ACTION: &'static str = "StatusNotification";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for StatusNotificationRequest {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.error_code)
            .map_err(|error| error.in_field("errorCode"))?;
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        Ok(())
    }
}
