// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct StopTransactionRequest {
    #[cfg_attr(feature = "serde", serde(rename = "idTag"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub id_tag: Option<super::IdTag>,
    #[cfg_attr(feature = "serde", serde(rename = "meterStop"))]
    pub meter_stop: i64,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub reason: Option<Reason>,
    pub timestamp: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(rename = "transactionData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_data: Option<alloc::vec::Vec<TransactionDataItem>>,
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    pub transaction_id: i64,
}
#[cfg(feature = "alloc")]
impl crate::Action for StopTransactionRequest {
    const ACTION: &'static str = "StopTransaction";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct StopTransactionRequest<
    const STOP_TRANSACTION_REQUEST_TRANSACTION_DATA_CAP: usize = 8usize,
    const TRANSACTION_DATA_ITEM_SAMPLED_VALUE_CAP: usize = 8usize,
    const SAMPLED_VALUE_ITEM_VALUE_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "idTag"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub id_tag: Option<super::IdTag>,
    #[cfg_attr(feature = "serde", serde(rename = "meterStop"))]
    pub meter_stop: i64,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub reason: Option<Reason>,
    pub timestamp: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(rename = "transactionData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_data: Option<
        heapless::Vec<
            TransactionDataItem<
                TRANSACTION_DATA_ITEM_SAMPLED_VALUE_CAP,
                SAMPLED_VALUE_ITEM_VALUE_CAP,
            >,
            STOP_TRANSACTION_REQUEST_TRANSACTION_DATA_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    pub transaction_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<
    const STOP_TRANSACTION_REQUEST_TRANSACTION_DATA_CAP: usize,
    const TRANSACTION_DATA_ITEM_SAMPLED_VALUE_CAP: usize,
    const SAMPLED_VALUE_ITEM_VALUE_CAP: usize,
> crate::Action
for StopTransactionRequest<
    STOP_TRANSACTION_REQUEST_TRANSACTION_DATA_CAP,
    TRANSACTION_DATA_ITEM_SAMPLED_VALUE_CAP,
    SAMPLED_VALUE_ITEM_VALUE_CAP,
> {
    const ACTION: &'static str = "StopTransaction";
}
