// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TriggerMessageRequest {
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "requestedMessage"))]
    pub requested_message: TriggerMessageRequestRequestedMessage,
}
impl crate::Action for TriggerMessageRequest {
    const ACTION: &'static str = "TriggerMessage";
}
#[cfg(feature = "validate")]
impl crate::validate::Validate for TriggerMessageRequest {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.requested_message)
            .map_err(|error| error.in_field("requestedMessage"))?;
        Ok(())
    }
}
