// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AFRRSignalRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Value of signal in _v2xSignalWattCurve_.
    pub signal: i64,
    /// Time when signal becomes active.
    pub timestamp: alloc::string::String,
}
#[cfg(feature = "alloc")]
impl crate::Action for AFRRSignalRequest {
    const ACTION: &'static str = "AFRRSignal";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AFRRSignalRequest<
    const A_F_R_R_SIGNAL_REQUEST_TIMESTAMP_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// Value of signal in _v2xSignalWattCurve_.
    pub signal: i64,
    /// Time when signal becomes active.
    pub timestamp: heapless::String<A_F_R_R_SIGNAL_REQUEST_TIMESTAMP_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<const A_F_R_R_SIGNAL_REQUEST_TIMESTAMP_CAP: usize> crate::Action
for AFRRSignalRequest<A_F_R_R_SIGNAL_REQUEST_TIMESTAMP_CAP> {
    const ACTION: &'static str = "AFRRSignal";
}
