// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AFRRSignalRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// Value of signal in _v2xSignalWattCurve_.
    pub signal: i64,
    /// Time when signal becomes active.
    pub timestamp: crate::OcppTimestamp,
}
impl<CustomDataType> crate::Action for AFRRSignalRequest<CustomDataType> {
    const ACTION: &'static str = "AFRRSignal";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate for AFRRSignalRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        Ok(())
    }
}
