// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AdjustPeriodicEventStreamRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    pub id: i64,
    pub params: PeriodicEventStreamParams<CustomDataType>,
}
impl<CustomDataType> crate::Action for AdjustPeriodicEventStreamRequest<CustomDataType> {
    const ACTION: &'static str = "AdjustPeriodicEventStream";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for AdjustPeriodicEventStreamRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_i64(self.id, 0i64)
            .map_err(|error| error.in_field("id"))?;
        crate::validate::Validate::validate(&self.params)
            .map_err(|error| error.in_field("params"))?;
        Ok(())
    }
}
