// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CancelReservationRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// Id of the reservation to cancel.
    #[cfg_attr(feature = "serde", serde(rename = "reservationId"))]
    pub reservation_id: i64,
}
impl<CustomDataType> crate::Action for CancelReservationRequest<CustomDataType> {
    const ACTION: &'static str = "CancelReservation";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for CancelReservationRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_i64(self.reservation_id, 0i64)
            .map_err(|error| error.in_field("reservationId"))?;
        Ok(())
    }
}
