// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ChangeAvailabilityRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse: Option<EVSE<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "operationalStatus"))]
    pub operational_status: OperationalStatusEnum,
}
impl<CustomDataType> crate::Action for ChangeAvailabilityRequest<CustomDataType> {
    const ACTION: &'static str = "ChangeAvailability";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for ChangeAvailabilityRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.evse {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("evse"))?;
        }
        crate::validate::Validate::validate(&self.operational_status)
            .map_err(|error| error.in_field("operationalStatus"))?;
        Ok(())
    }
}
