// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ChangeAvailabilityRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse: Option<EVSE>,
    #[cfg_attr(feature = "serde", serde(rename = "operationalStatus"))]
    pub operational_status: OperationalStatusEnum,
}
impl crate::Action for ChangeAvailabilityRequest {
    const ACTION: &'static str = "ChangeAvailability";
}
