// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ChangeTransactionTariffRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    pub tariff: Tariff,
    /// Transaction id for new tariff.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    pub transaction_id: heapless::String<36usize>,
}
#[cfg(feature = "alloc")]
impl crate::Action for ChangeTransactionTariffRequest {
    const ACTION: &'static str = "ChangeTransactionTariff";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ChangeTransactionTariffRequest<
    const TARIFF_TIME_PRICES_CAP: usize = 16usize,
    const TARIFF_CONDITIONS_END_TIME_OF_DAY_CAP: usize = 1024usize,
    const TARIFF_CONDITIONS_START_TIME_OF_DAY_CAP: usize = 1024usize,
    const TARIFF_CONDITIONS_VALID_FROM_DATE_CAP: usize = 1024usize,
    const TARIFF_CONDITIONS_VALID_TO_DATE_CAP: usize = 1024usize,
    const TARIFF_ENERGY_PRICES_CAP: usize = 16usize,
    const TARIFF_FIXED_PRICES_CAP: usize = 16usize,
    const TARIFF_CONDITIONS_FIXED_END_TIME_OF_DAY_CAP: usize = 1024usize,
    const TARIFF_CONDITIONS_FIXED_START_TIME_OF_DAY_CAP: usize = 1024usize,
    const TARIFF_CONDITIONS_FIXED_VALID_FROM_DATE_CAP: usize = 1024usize,
    const TARIFF_CONDITIONS_FIXED_VALID_TO_DATE_CAP: usize = 1024usize,
    const TARIFF_VALID_FROM_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    pub tariff: Tariff<
        TARIFF_TIME_PRICES_CAP,
        TARIFF_CONDITIONS_END_TIME_OF_DAY_CAP,
        TARIFF_CONDITIONS_START_TIME_OF_DAY_CAP,
        TARIFF_CONDITIONS_VALID_FROM_DATE_CAP,
        TARIFF_CONDITIONS_VALID_TO_DATE_CAP,
        TARIFF_ENERGY_PRICES_CAP,
        TARIFF_FIXED_PRICES_CAP,
        TARIFF_CONDITIONS_FIXED_END_TIME_OF_DAY_CAP,
        TARIFF_CONDITIONS_FIXED_START_TIME_OF_DAY_CAP,
        TARIFF_CONDITIONS_FIXED_VALID_FROM_DATE_CAP,
        TARIFF_CONDITIONS_FIXED_VALID_TO_DATE_CAP,
        TARIFF_VALID_FROM_CAP,
    >,
    /// Transaction id for new tariff.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    pub transaction_id: heapless::String<36usize>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const TARIFF_TIME_PRICES_CAP: usize,
    const TARIFF_CONDITIONS_END_TIME_OF_DAY_CAP: usize,
    const TARIFF_CONDITIONS_START_TIME_OF_DAY_CAP: usize,
    const TARIFF_CONDITIONS_VALID_FROM_DATE_CAP: usize,
    const TARIFF_CONDITIONS_VALID_TO_DATE_CAP: usize,
    const TARIFF_ENERGY_PRICES_CAP: usize,
    const TARIFF_FIXED_PRICES_CAP: usize,
    const TARIFF_CONDITIONS_FIXED_END_TIME_OF_DAY_CAP: usize,
    const TARIFF_CONDITIONS_FIXED_START_TIME_OF_DAY_CAP: usize,
    const TARIFF_CONDITIONS_FIXED_VALID_FROM_DATE_CAP: usize,
    const TARIFF_CONDITIONS_FIXED_VALID_TO_DATE_CAP: usize,
    const TARIFF_VALID_FROM_CAP: usize,
> crate::Action
for ChangeTransactionTariffRequest<
    TARIFF_TIME_PRICES_CAP,
    TARIFF_CONDITIONS_END_TIME_OF_DAY_CAP,
    TARIFF_CONDITIONS_START_TIME_OF_DAY_CAP,
    TARIFF_CONDITIONS_VALID_FROM_DATE_CAP,
    TARIFF_CONDITIONS_VALID_TO_DATE_CAP,
    TARIFF_ENERGY_PRICES_CAP,
    TARIFF_FIXED_PRICES_CAP,
    TARIFF_CONDITIONS_FIXED_END_TIME_OF_DAY_CAP,
    TARIFF_CONDITIONS_FIXED_START_TIME_OF_DAY_CAP,
    TARIFF_CONDITIONS_FIXED_VALID_FROM_DATE_CAP,
    TARIFF_CONDITIONS_FIXED_VALID_TO_DATE_CAP,
    TARIFF_VALID_FROM_CAP,
> {
    const ACTION: &'static str = "ChangeTransactionTariff";
}
