// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearedChargingLimitRequest<CustomDataType = crate::NoCustomData> {
    /// Source of the charging limit. Allowed values defined in Appendix as ChargingLimitSourceEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: heapless::String<20usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// EVSE Identifier.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
}
impl<CustomDataType> crate::Action for ClearedChargingLimitRequest<CustomDataType> {
    const ACTION: &'static str = "ClearedChargingLimit";
}
