// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearVariableMonitoringResponse {
    #[cfg_attr(feature = "serde", serde(rename = "clearMonitoringResult"))]
    pub clear_monitoring_result: alloc::vec::Vec<ClearMonitoringResult>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
}
#[cfg(feature = "alloc")]
impl crate::Action for ClearVariableMonitoringResponse {
    const ACTION: &'static str = "ClearVariableMonitoring";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearVariableMonitoringResponse<
    const CLEAR_VARIABLE_MONITORING_RESPONSE_CLEAR_MONITORING_RESULT_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "clearMonitoringResult"))]
    pub clear_monitoring_result: heapless::Vec<
        ClearMonitoringResult,
        CLEAR_VARIABLE_MONITORING_RESPONSE_CLEAR_MONITORING_RESULT_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const CLEAR_VARIABLE_MONITORING_RESPONSE_CLEAR_MONITORING_RESULT_CAP: usize,
> crate::Action
for ClearVariableMonitoringResponse<
    CLEAR_VARIABLE_MONITORING_RESPONSE_CLEAR_MONITORING_RESULT_CAP,
> {
    const ACTION: &'static str = "ClearVariableMonitoring";
}
