// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearTariffsResponse<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "clearTariffsResult"))]
    pub clear_tariffs_result: alloc::vec::Vec<ClearTariffsResult<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for ClearTariffsResponse<CustomDataType> {
    const ACTION: &'static str = "ClearTariffs";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate for ClearTariffsResponse<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.clear_tariffs_result.len(), 1usize)
            .map_err(|error| error.in_field("clearTariffsResult"))?;
        for (index, item) in self.clear_tariffs_result.iter().enumerate() {
            crate::validate::Validate::validate(item)
                .map_err(|error| error.in_index(index).in_field("clearTariffsResult"))?;
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearTariffsResponse<
    CustomDataType = crate::NoCustomData,
    const CLEAR_TARIFFS_RESPONSE_CLEAR_TARIFFS_RESULT_CAP: usize = 8usize,
    const STATUS_INFO_ADDITIONAL_INFO_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "clearTariffsResult"))]
    pub clear_tariffs_result: heapless::Vec<
        ClearTariffsResult<CustomDataType, STATUS_INFO_ADDITIONAL_INFO_CAP>,
        CLEAR_TARIFFS_RESPONSE_CLEAR_TARIFFS_RESULT_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const CLEAR_TARIFFS_RESPONSE_CLEAR_TARIFFS_RESULT_CAP: usize,
    const STATUS_INFO_ADDITIONAL_INFO_CAP: usize,
> crate::Action
for ClearTariffsResponse<
    CustomDataType,
    CLEAR_TARIFFS_RESPONSE_CLEAR_TARIFFS_RESULT_CAP,
    STATUS_INFO_ADDITIONAL_INFO_CAP,
> {
    const ACTION: &'static str = "ClearTariffs";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const CLEAR_TARIFFS_RESPONSE_CLEAR_TARIFFS_RESULT_CAP: usize,
    const STATUS_INFO_ADDITIONAL_INFO_CAP: usize,
> crate::validate::Validate
for ClearTariffsResponse<
    CustomDataType,
    CLEAR_TARIFFS_RESPONSE_CLEAR_TARIFFS_RESULT_CAP,
    STATUS_INFO_ADDITIONAL_INFO_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.clear_tariffs_result.len(), 1usize)
            .map_err(|error| error.in_field("clearTariffsResult"))?;
        for (index, item) in self.clear_tariffs_result.iter().enumerate() {
            crate::validate::Validate::validate(item)
                .map_err(|error| error.in_index(index).in_field("clearTariffsResult"))?;
        }
        Ok(())
    }
}
