// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearTariffsRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// When present only clear tariffs matching _tariffIds_ at EVSE _evseId_.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
    /// List of tariff Ids to clear. When absent clears all tariffs at _evseId_.
    #[cfg_attr(feature = "serde", serde(rename = "tariffIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tariff_ids: Option<alloc::vec::Vec<heapless::String<60usize>>>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for ClearTariffsRequest<CustomDataType> {
    const ACTION: &'static str = "ClearTariffs";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearTariffsRequest<
    CustomDataType = crate::NoCustomData,
    const CLEAR_TARIFFS_REQUEST_TARIFF_IDS_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// When present only clear tariffs matching _tariffIds_ at EVSE _evseId_.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
    /// List of tariff Ids to clear. When absent clears all tariffs at _evseId_.
    #[cfg_attr(feature = "serde", serde(rename = "tariffIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tariff_ids: Option<
        heapless::Vec<heapless::String<60usize>, CLEAR_TARIFFS_REQUEST_TARIFF_IDS_CAP>,
    >,
}
#[cfg(not(feature = "alloc"))]
impl<CustomDataType, const CLEAR_TARIFFS_REQUEST_TARIFF_IDS_CAP: usize> crate::Action
for ClearTariffsRequest<CustomDataType, CLEAR_TARIFFS_REQUEST_TARIFF_IDS_CAP> {
    const ACTION: &'static str = "ClearTariffs";
}
