// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearVariableMonitoringRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// List of the monitors to be cleared, identified by there Id.
    pub id: alloc::vec::Vec<i64>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for ClearVariableMonitoringRequest<CustomDataType> {
    const ACTION: &'static str = "ClearVariableMonitoring";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for ClearVariableMonitoringRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.id.len(), 1usize)
            .map_err(|error| error.in_field("id"))?;
        for (index, item) in self.id.iter().enumerate() {
            crate::validate::check_min_i64(*item, 0i64)
                .map_err(|error| error.in_index(index).in_field("id"))?;
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearVariableMonitoringRequest<
    CustomDataType = crate::NoCustomData,
    const CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// List of the monitors to be cleared, identified by there Id.
    pub id: heapless::Vec<i64, CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<CustomDataType, const CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP: usize> crate::Action
for ClearVariableMonitoringRequest<
    CustomDataType,
    CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP,
> {
    const ACTION: &'static str = "ClearVariableMonitoring";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP: usize,
> crate::validate::Validate
for ClearVariableMonitoringRequest<
    CustomDataType,
    CLEAR_VARIABLE_MONITORING_REQUEST_ID_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.id.len(), 1usize)
            .map_err(|error| error.in_field("id"))?;
        for (index, item) in self.id.iter().enumerate() {
            crate::validate::check_min_i64(*item, 0i64)
                .map_err(|error| error.in_index(index).in_field("id"))?;
        }
        Ok(())
    }
}
