// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CustomerInformationRequest<CustomDataType = crate::NoCustomData> {
    /// Flag indicating whether the Charging Station should clear all information about the customer referred to.
    pub clear: bool,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "customerCertificate"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub customer_certificate: Option<CertificateHashData<CustomDataType>>,
    /// A (e.g. vendor specific) identifier of the customer this request refers to. This field contains a custom identifier other than IdToken and Certificate.
    /// One of the possible identifiers (customerIdentifier, customerIdToken or customerCertificate) should be in the request message.
    #[cfg_attr(feature = "serde", serde(rename = "customerIdentifier"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub customer_identifier: Option<heapless::String<64usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub id_token: Option<IdToken<CustomDataType>>,
    /// Flag indicating whether the Charging Station should return NotifyCustomerInformationRequest messages containing information about the customer referred to.
    pub report: bool,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for CustomerInformationRequest<CustomDataType> {
    const ACTION: &'static str = "CustomerInformation";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for CustomerInformationRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.customer_certificate {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("customerCertificate"))?;
        }
        if let Some(value) = &self.id_token {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("idToken"))?;
        }
        crate::validate::check_min_i64(self.request_id, 0i64)
            .map_err(|error| error.in_field("requestId"))?;
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CustomerInformationRequest<
    CustomDataType = crate::NoCustomData,
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize = 8usize,
> {
    /// Flag indicating whether the Charging Station should clear all information about the customer referred to.
    pub clear: bool,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "customerCertificate"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub customer_certificate: Option<CertificateHashData<CustomDataType>>,
    /// A (e.g. vendor specific) identifier of the customer this request refers to. This field contains a custom identifier other than IdToken and Certificate.
    /// One of the possible identifiers (customerIdentifier, customerIdToken or customerCertificate) should be in the request message.
    #[cfg_attr(feature = "serde", serde(rename = "customerIdentifier"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub customer_identifier: Option<heapless::String<64usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub id_token: Option<IdToken<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP>>,
    /// Flag indicating whether the Charging Station should return NotifyCustomerInformationRequest messages containing information about the customer referred to.
    pub report: bool,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<CustomDataType, const ID_TOKEN_ADDITIONAL_INFO_CAP: usize> crate::Action
for CustomerInformationRequest<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP> {
    const ACTION: &'static str = "CustomerInformation";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<CustomDataType, const ID_TOKEN_ADDITIONAL_INFO_CAP: usize> crate::validate::Validate
for CustomerInformationRequest<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.customer_certificate {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("customerCertificate"))?;
        }
        if let Some(value) = &self.id_token {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("idToken"))?;
        }
        crate::validate::check_min_i64(self.request_id, 0i64)
            .map_err(|error| error.in_field("requestId"))?;
        Ok(())
    }
}
