// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Get15118EVCertificateResponse {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// *(2/1)* Raw CertificateInstallationRes response for the EV, Base64 encoded. +
    /// Extended to support ISO 15118-20 certificates. The minimum supported length is 17000. If a longer _exiResponse_ is supported, then the supported length must be communicated in variable OCPPCommCtrlr.FieldLength\[ "Get15118EVCertificateResponse.exiResponse" \].
    #[cfg_attr(feature = "serde", serde(rename = "exiResponse"))]
    pub exi_response: heapless::String<17000usize>,
    /// *(2.1)* Number of contracts that can be retrieved with additional requests.
    #[cfg_attr(feature = "serde", serde(rename = "remainingContracts"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub remaining_contracts: Option<i64>,
    pub status: Iso15118EVCertificateStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<StatusInfo>,
}
impl crate::Action for Get15118EVCertificateResponse {
    const ACTION: &'static str = "Get15118EVCertificate";
}
