// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetTariffsRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// EVSE id to get tariff from. When _evseId_ = 0, this gets tariffs from all EVSEs.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
}
impl<CustomDataType> crate::Action for GetTariffsRequest<CustomDataType> {
    const ACTION: &'static str = "GetTariffs";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate for GetTariffsRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_i64(self.evse_id, 0i64)
            .map_err(|error| error.in_field("evseId"))?;
        Ok(())
    }
}
