// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetCertificateChainStatusResponse<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "certificateStatus"))]
    pub certificate_status: heapless::Vec<CertificateStatus<CustomDataType>, 4usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
impl<CustomDataType> crate::Action
for GetCertificateChainStatusResponse<CustomDataType> {
    const ACTION: &'static str = "GetCertificateChainStatus";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for GetCertificateChainStatusResponse<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.certificate_status.len(), 1usize)
            .map_err(|error| error.in_field("certificateStatus"))?;
        for (index, item) in self.certificate_status.iter().enumerate() {
            crate::validate::Validate::validate(item)
                .map_err(|error| error.in_index(index).in_field("certificateStatus"))?;
        }
        Ok(())
    }
}
