// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetMonitoringReportRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "componentVariable"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub component_variable: Option<alloc::vec::Vec<ComponentVariable<CustomDataType>>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// This field contains criteria for components for which a monitoring report is requested
    #[cfg_attr(feature = "serde", serde(rename = "monitoringCriteria"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitoring_criteria: Option<heapless::Vec<MonitoringCriterionEnum, 3usize>>,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for GetMonitoringReportRequest<CustomDataType> {
    const ACTION: &'static str = "GetMonitoringReport";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for GetMonitoringReportRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.component_variable {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("componentVariable"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| {
                        error.in_index(index).in_field("componentVariable")
                    })?;
            }
        }
        if let Some(value) = &self.monitoring_criteria {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("monitoringCriteria"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| {
                        error.in_index(index).in_field("monitoringCriteria")
                    })?;
            }
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetMonitoringReportRequest<
    CustomDataType = crate::NoCustomData,
    const GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "componentVariable"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub component_variable: Option<
        heapless::Vec<
            ComponentVariable<CustomDataType>,
            GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// This field contains criteria for components for which a monitoring report is requested
    #[cfg_attr(feature = "serde", serde(rename = "monitoringCriteria"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitoring_criteria: Option<heapless::Vec<MonitoringCriterionEnum, 3usize>>,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP: usize,
> crate::Action
for GetMonitoringReportRequest<
    CustomDataType,
    GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP,
> {
    const ACTION: &'static str = "GetMonitoringReport";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP: usize,
> crate::validate::Validate
for GetMonitoringReportRequest<
    CustomDataType,
    GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.component_variable {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("componentVariable"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| {
                        error.in_index(index).in_field("componentVariable")
                    })?;
            }
        }
        if let Some(value) = &self.monitoring_criteria {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("monitoringCriteria"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| {
                        error.in_index(index).in_field("monitoringCriteria")
                    })?;
            }
        }
        Ok(())
    }
}
