// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetMonitoringReportRequest {
    #[cfg_attr(feature = "serde", serde(rename = "componentVariable"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub component_variable: Option<alloc::vec::Vec<ComponentVariable>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// This field contains criteria for components for which a monitoring report is requested
    #[cfg_attr(feature = "serde", serde(rename = "monitoringCriteria"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitoring_criteria: Option<heapless::Vec<MonitoringCriterionEnum, 3usize>>,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(feature = "alloc")]
impl crate::Action for GetMonitoringReportRequest {
    const ACTION: &'static str = "GetMonitoringReport";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetMonitoringReportRequest<
    const GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "componentVariable"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub component_variable: Option<
        heapless::Vec<
            ComponentVariable,
            GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// This field contains criteria for components for which a monitoring report is requested
    #[cfg_attr(feature = "serde", serde(rename = "monitoringCriteria"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitoring_criteria: Option<heapless::Vec<MonitoringCriterionEnum, 3usize>>,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<const GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP: usize> crate::Action
for GetMonitoringReportRequest<GET_MONITORING_REPORT_REQUEST_COMPONENT_VARIABLE_CAP> {
    const ACTION: &'static str = "GetMonitoringReport";
}
