// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetDERControlRequest<CustomDataType = crate::NoCustomData> {
    /// Id of setting to get. When omitted all settings for _controlType_ are retrieved.
    #[cfg_attr(feature = "serde", serde(rename = "controlId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub control_id: Option<heapless::String<36usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "controlType"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub control_type: Option<DERControlEnum>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// True: get a default DER control. False: get a scheduled control.
    #[cfg_attr(feature = "serde", serde(rename = "isDefault"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub is_default: Option<bool>,
    /// RequestId to be used in ReportDERControlRequest.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
impl<CustomDataType> crate::Action for GetDERControlRequest<CustomDataType> {
    const ACTION: &'static str = "GetDERControl";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate for GetDERControlRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.control_type {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("controlType"))?;
        }
        Ok(())
    }
}
