// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetInstalledCertificateIdsRequest {
    /// Indicates the type of certificates requested. When omitted, all certificate types are requested.
    #[cfg_attr(feature = "serde", serde(rename = "certificateType"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub certificate_type: Option<alloc::vec::Vec<GetCertificateIdUseEnum>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
}
#[cfg(feature = "alloc")]
impl crate::Action for GetInstalledCertificateIdsRequest {
    const ACTION: &'static str = "GetInstalledCertificateIds";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetInstalledCertificateIdsRequest<
    const GET_INSTALLED_CERTIFICATE_IDS_REQUEST_CERTIFICATE_TYPE_CAP: usize = 16usize,
> {
    /// Indicates the type of certificates requested. When omitted, all certificate types are requested.
    #[cfg_attr(feature = "serde", serde(rename = "certificateType"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub certificate_type: Option<
        heapless::Vec<
            GetCertificateIdUseEnum,
            GET_INSTALLED_CERTIFICATE_IDS_REQUEST_CERTIFICATE_TYPE_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const GET_INSTALLED_CERTIFICATE_IDS_REQUEST_CERTIFICATE_TYPE_CAP: usize,
> crate::Action
for GetInstalledCertificateIdsRequest<
    GET_INSTALLED_CERTIFICATE_IDS_REQUEST_CERTIFICATE_TYPE_CAP,
> {
    const ACTION: &'static str = "GetInstalledCertificateIds";
}
