// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyCustomerInformationRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// (Part of) the requested data. No format specified in which the data is returned. Should be human readable.
    pub data: heapless::String<512usize>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: alloc::string::String,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl crate::Action for NotifyCustomerInformationRequest {
    const ACTION: &'static str = "NotifyCustomerInformation";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyCustomerInformationRequest<
    const NOTIFY_CUSTOMER_INFORMATION_REQUEST_GENERATED_AT_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// (Part of) the requested data. No format specified in which the data is returned. Should be human readable.
    pub data: heapless::String<512usize>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: heapless::String<
        NOTIFY_CUSTOMER_INFORMATION_REQUEST_GENERATED_AT_CAP,
    >,
    /// The Id of the request.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<const NOTIFY_CUSTOMER_INFORMATION_REQUEST_GENERATED_AT_CAP: usize> crate::Action
for NotifyCustomerInformationRequest<
    NOTIFY_CUSTOMER_INFORMATION_REQUEST_GENERATED_AT_CAP,
> {
    const ACTION: &'static str = "NotifyCustomerInformation";
}
