// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyWebPaymentStartedRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// EVSE id for which transaction is requested.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Timeout value in seconds after which no result of web payment process (e.g. QR code scanning) is to be expected anymore.
    pub timeout: i64,
}
impl<CustomDataType> crate::Action for NotifyWebPaymentStartedRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyWebPaymentStarted";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for NotifyWebPaymentStartedRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_i64(self.evse_id, 0i64)
            .map_err(|error| error.in_field("evseId"))?;
        Ok(())
    }
}
