// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyPeriodicEventStream<CustomDataType = crate::NoCustomData> {
    /// Base timestamp to add to time offset of values.
    pub basetime: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    pub data: alloc::vec::Vec<StreamDataElement<CustomDataType>>,
    /// Id of stream.
    pub id: i64,
    /// Number of data elements still pending to be sent.
    pub pending: i64,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyPeriodicEventStream<CustomDataType> {
    const ACTION: &'static str = "NotifyPeriodicEventStream";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyPeriodicEventStream<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_PERIODIC_EVENT_STREAM_DATA_CAP: usize = 8usize,
    const STREAM_DATA_ELEMENT_V_CAP: usize = 1024usize,
> {
    /// Base timestamp to add to time offset of values.
    pub basetime: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    pub data: heapless::Vec<
        StreamDataElement<CustomDataType, STREAM_DATA_ELEMENT_V_CAP>,
        NOTIFY_PERIODIC_EVENT_STREAM_DATA_CAP,
    >,
    /// Id of stream.
    pub id: i64,
    /// Number of data elements still pending to be sent.
    pub pending: i64,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_PERIODIC_EVENT_STREAM_DATA_CAP: usize,
    const STREAM_DATA_ELEMENT_V_CAP: usize,
> crate::Action
for NotifyPeriodicEventStream<
    CustomDataType,
    NOTIFY_PERIODIC_EVENT_STREAM_DATA_CAP,
    STREAM_DATA_ELEMENT_V_CAP,
> {
    const ACTION: &'static str = "NotifyPeriodicEventStream";
}
