// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDisplayMessagesRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "messageInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub message_info: Option<alloc::vec::Vec<MessageInfo<CustomDataType>>>,
    /// The id of the &lt;&lt;getdisplaymessagesrequest,GetDisplayMessagesRequest&gt;&gt; that requested this message.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// "to be continued" indicator. Indicates whether another part of the report follows in an upcoming NotifyDisplayMessagesRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyDisplayMessagesRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyDisplayMessages";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDisplayMessagesRequest<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_DISPLAY_MESSAGES_REQUEST_MESSAGE_INFO_CAP: usize = 8usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "messageInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub message_info: Option<
        heapless::Vec<
            MessageInfo<CustomDataType, MESSAGE_CONTENT_CONTENT_CAP>,
            NOTIFY_DISPLAY_MESSAGES_REQUEST_MESSAGE_INFO_CAP,
        >,
    >,
    /// The id of the &lt;&lt;getdisplaymessagesrequest,GetDisplayMessagesRequest&gt;&gt; that requested this message.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// "to be continued" indicator. Indicates whether another part of the report follows in an upcoming NotifyDisplayMessagesRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_DISPLAY_MESSAGES_REQUEST_MESSAGE_INFO_CAP: usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize,
> crate::Action
for NotifyDisplayMessagesRequest<
    CustomDataType,
    NOTIFY_DISPLAY_MESSAGES_REQUEST_MESSAGE_INFO_CAP,
    MESSAGE_CONTENT_CONTENT_CAP,
> {
    const ACTION: &'static str = "NotifyDisplayMessages";
}
