// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDERStartStopRequest<CustomDataType = crate::NoCustomData> {
    /// Id of the started or stopped DER control.
    /// Corresponds to the _controlId_ of the SetDERControlRequest.
    #[cfg_attr(feature = "serde", serde(rename = "controlId"))]
    pub control_id: heapless::String<36usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// True if DER control has started. False if it has ended.
    pub started: bool,
    /// List of controlIds that are superseded as a result of this control starting.
    #[cfg_attr(feature = "serde", serde(rename = "supersededIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub superseded_ids: Option<alloc::vec::Vec<heapless::String<36usize>>>,
    /// Time of start or end of event.
    pub timestamp: crate::OcppTimestamp,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyDERStartStopRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyDERStartStop";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDERStartStopRequest<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_D_E_R_START_STOP_REQUEST_SUPERSEDED_IDS_CAP: usize = 8usize,
> {
    /// Id of the started or stopped DER control.
    /// Corresponds to the _controlId_ of the SetDERControlRequest.
    #[cfg_attr(feature = "serde", serde(rename = "controlId"))]
    pub control_id: heapless::String<36usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// True if DER control has started. False if it has ended.
    pub started: bool,
    /// List of controlIds that are superseded as a result of this control starting.
    #[cfg_attr(feature = "serde", serde(rename = "supersededIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub superseded_ids: Option<
        heapless::Vec<
            heapless::String<36usize>,
            NOTIFY_D_E_R_START_STOP_REQUEST_SUPERSEDED_IDS_CAP,
        >,
    >,
    /// Time of start or end of event.
    pub timestamp: crate::OcppTimestamp,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_D_E_R_START_STOP_REQUEST_SUPERSEDED_IDS_CAP: usize,
> crate::Action
for NotifyDERStartStopRequest<
    CustomDataType,
    NOTIFY_D_E_R_START_STOP_REQUEST_SUPERSEDED_IDS_CAP,
> {
    const ACTION: &'static str = "NotifyDERStartStop";
}
