// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyEVChargingScheduleRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    pub charging_schedule: ChargingSchedule<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The charging schedule contained in this notification applies to an EVSE. EvseId must be &gt; 0.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// *(2.1)* True when power tolerance is accepted by EV.
    /// This value is taken from EVPowerProfile.PowerToleranceAcceptance in the ISO 15118-20 PowerDeliverReq message..
    #[cfg_attr(feature = "serde", serde(rename = "powerToleranceAcceptance"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub power_tolerance_acceptance: Option<bool>,
    /// *(2.1)* Id  of the _chargingSchedule_ that EV selected from the provided ChargingProfile.
    #[cfg_attr(feature = "serde", serde(rename = "selectedChargingScheduleId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub selected_charging_schedule_id: Option<i64>,
    /// Periods contained in the charging profile are relative to this point in time.
    #[cfg_attr(feature = "serde", serde(rename = "timeBase"))]
    pub time_base: crate::OcppTimestamp,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyEVChargingScheduleRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyEVChargingSchedule";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyEVChargingScheduleRequest<
    CustomDataType = crate::NoCustomData,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize = 1024usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize = 8usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize = 8usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    pub charging_schedule: ChargingSchedule<
        CustomDataType,
        ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
        ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
        CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
        CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
        CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
        PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
        SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The charging schedule contained in this notification applies to an EVSE. EvseId must be &gt; 0.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// *(2.1)* True when power tolerance is accepted by EV.
    /// This value is taken from EVPowerProfile.PowerToleranceAcceptance in the ISO 15118-20 PowerDeliverReq message..
    #[cfg_attr(feature = "serde", serde(rename = "powerToleranceAcceptance"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub power_tolerance_acceptance: Option<bool>,
    /// *(2.1)* Id  of the _chargingSchedule_ that EV selected from the provided ChargingProfile.
    #[cfg_attr(feature = "serde", serde(rename = "selectedChargingScheduleId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub selected_charging_schedule_id: Option<i64>,
    /// Periods contained in the charging profile are relative to this point in time.
    #[cfg_attr(feature = "serde", serde(rename = "timeBase"))]
    pub time_base: crate::OcppTimestamp,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
> crate::Action
for NotifyEVChargingScheduleRequest<
    CustomDataType,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
    PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
> {
    const ACTION: &'static str = "NotifyEVChargingSchedule";
}
