// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyEVChargingScheduleRequest {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    pub charging_schedule: ChargingSchedule,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The charging schedule contained in this notification applies to an EVSE. EvseId must be &gt; 0.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// *(2.1)* True when power tolerance is accepted by EV.
    /// This value is taken from EVPowerProfile.PowerToleranceAcceptance in the ISO 15118-20 PowerDeliverReq message..
    #[cfg_attr(feature = "serde", serde(rename = "powerToleranceAcceptance"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub power_tolerance_acceptance: Option<bool>,
    /// *(2.1)* Id  of the _chargingSchedule_ that EV selected from the provided ChargingProfile.
    #[cfg_attr(feature = "serde", serde(rename = "selectedChargingScheduleId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub selected_charging_schedule_id: Option<i64>,
    /// Periods contained in the charging profile are relative to this point in time.
    #[cfg_attr(feature = "serde", serde(rename = "timeBase"))]
    pub time_base: alloc::string::String,
}
#[cfg(feature = "alloc")]
impl crate::Action for NotifyEVChargingScheduleRequest {
    const ACTION: &'static str = "NotifyEVChargingSchedule";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyEVChargingScheduleRequest<
    const ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP: usize = 1024usize,
    const PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP: usize = 1024usize,
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize = 1024usize,
    const NOTIFY_E_V_CHARGING_SCHEDULE_REQUEST_TIME_BASE_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingSchedule"))]
    pub charging_schedule: ChargingSchedule<
        ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP,
        PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP,
        CHARGING_SCHEDULE_START_SCHEDULE_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The charging schedule contained in this notification applies to an EVSE. EvseId must be &gt; 0.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// *(2.1)* True when power tolerance is accepted by EV.
    /// This value is taken from EVPowerProfile.PowerToleranceAcceptance in the ISO 15118-20 PowerDeliverReq message..
    #[cfg_attr(feature = "serde", serde(rename = "powerToleranceAcceptance"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub power_tolerance_acceptance: Option<bool>,
    /// *(2.1)* Id  of the _chargingSchedule_ that EV selected from the provided ChargingProfile.
    #[cfg_attr(feature = "serde", serde(rename = "selectedChargingScheduleId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub selected_charging_schedule_id: Option<i64>,
    /// Periods contained in the charging profile are relative to this point in time.
    #[cfg_attr(feature = "serde", serde(rename = "timeBase"))]
    pub time_base: heapless::String<NOTIFY_E_V_CHARGING_SCHEDULE_REQUEST_TIME_BASE_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP: usize,
    const PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP: usize,
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize,
    const NOTIFY_E_V_CHARGING_SCHEDULE_REQUEST_TIME_BASE_CAP: usize,
> crate::Action
for NotifyEVChargingScheduleRequest<
    ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP,
    PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP,
    CHARGING_SCHEDULE_START_SCHEDULE_CAP,
    NOTIFY_E_V_CHARGING_SCHEDULE_REQUEST_TIME_BASE_CAP,
> {
    const ACTION: &'static str = "NotifyEVChargingSchedule";
}
