// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifySettlementRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The payment reference received from the payment terminal and is used as the value for _idToken_.
    #[cfg_attr(feature = "serde", serde(rename = "pspRef"))]
    pub psp_ref: heapless::String<255usize>,
    #[cfg_attr(feature = "serde", serde(rename = "receiptId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_id: Option<heapless::String<50usize>>,
    /// The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
    #[cfg_attr(feature = "serde", serde(rename = "receiptUrl"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_url: Option<heapless::String<2000usize>>,
    /// The amount that was settled, or attempted to be settled (in case of failure).
    #[cfg_attr(feature = "serde", serde(rename = "settlementAmount"))]
    pub settlement_amount: f64,
    /// The time when the settlement was done.
    #[cfg_attr(feature = "serde", serde(rename = "settlementTime"))]
    pub settlement_time: alloc::string::String,
    pub status: PaymentStatusEnum,
    /// Additional information from payment terminal/payment process.
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<heapless::String<500usize>>,
    /// The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_id: Option<heapless::String<36usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vatCompany"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_company: Option<Address>,
    /// VAT number for a company receipt.
    #[cfg_attr(feature = "serde", serde(rename = "vatNumber"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_number: Option<heapless::String<20usize>>,
}
#[cfg(feature = "alloc")]
impl crate::Action for NotifySettlementRequest {
    const ACTION: &'static str = "NotifySettlement";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifySettlementRequest<
    const NOTIFY_SETTLEMENT_REQUEST_SETTLEMENT_TIME_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The payment reference received from the payment terminal and is used as the value for _idToken_.
    #[cfg_attr(feature = "serde", serde(rename = "pspRef"))]
    pub psp_ref: heapless::String<255usize>,
    #[cfg_attr(feature = "serde", serde(rename = "receiptId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_id: Option<heapless::String<50usize>>,
    /// The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
    #[cfg_attr(feature = "serde", serde(rename = "receiptUrl"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_url: Option<heapless::String<2000usize>>,
    /// The amount that was settled, or attempted to be settled (in case of failure).
    #[cfg_attr(feature = "serde", serde(rename = "settlementAmount"))]
    pub settlement_amount: f64,
    /// The time when the settlement was done.
    #[cfg_attr(feature = "serde", serde(rename = "settlementTime"))]
    pub settlement_time: heapless::String<NOTIFY_SETTLEMENT_REQUEST_SETTLEMENT_TIME_CAP>,
    pub status: PaymentStatusEnum,
    /// Additional information from payment terminal/payment process.
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<heapless::String<500usize>>,
    /// The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_id: Option<heapless::String<36usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vatCompany"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_company: Option<Address>,
    /// VAT number for a company receipt.
    #[cfg_attr(feature = "serde", serde(rename = "vatNumber"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_number: Option<heapless::String<20usize>>,
}
#[cfg(not(feature = "alloc"))]
impl<const NOTIFY_SETTLEMENT_REQUEST_SETTLEMENT_TIME_CAP: usize> crate::Action
for NotifySettlementRequest<NOTIFY_SETTLEMENT_REQUEST_SETTLEMENT_TIME_CAP> {
    const ACTION: &'static str = "NotifySettlement";
}
