// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDERStartStopRequest {
    /// Id of the started or stopped DER control.
    /// Corresponds to the _controlId_ of the SetDERControlRequest.
    #[cfg_attr(feature = "serde", serde(rename = "controlId"))]
    pub control_id: heapless::String<36usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// True if DER control has started. False if it has ended.
    pub started: bool,
    /// List of controlIds that are superseded as a result of this control starting.
    #[cfg_attr(feature = "serde", serde(rename = "supersededIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub superseded_ids: Option<heapless::Vec<heapless::String<36usize>, 24usize>>,
    /// Time of start or end of event.
    pub timestamp: alloc::string::String,
}
#[cfg(feature = "alloc")]
impl crate::Action for NotifyDERStartStopRequest {
    const ACTION: &'static str = "NotifyDERStartStop";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDERStartStopRequest<
    const NOTIFY_D_E_R_START_STOP_REQUEST_TIMESTAMP_CAP: usize = 1024usize,
> {
    /// Id of the started or stopped DER control.
    /// Corresponds to the _controlId_ of the SetDERControlRequest.
    #[cfg_attr(feature = "serde", serde(rename = "controlId"))]
    pub control_id: heapless::String<36usize>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// True if DER control has started. False if it has ended.
    pub started: bool,
    /// List of controlIds that are superseded as a result of this control starting.
    #[cfg_attr(feature = "serde", serde(rename = "supersededIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub superseded_ids: Option<heapless::Vec<heapless::String<36usize>, 24usize>>,
    /// Time of start or end of event.
    pub timestamp: heapless::String<NOTIFY_D_E_R_START_STOP_REQUEST_TIMESTAMP_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<const NOTIFY_D_E_R_START_STOP_REQUEST_TIMESTAMP_CAP: usize> crate::Action
for NotifyDERStartStopRequest<NOTIFY_D_E_R_START_STOP_REQUEST_TIMESTAMP_CAP> {
    const ACTION: &'static str = "NotifyDERStartStop";
}
