// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyMonitoringReportRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitor: Option<alloc::vec::Vec<MonitoringData<CustomDataType>>>,
    /// The id of the GetMonitoringRequest that requested this report.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyMonitoringReportRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyMonitoringReport";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for NotifyMonitoringReportRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.monitor {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("monitor"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| error.in_index(index).in_field("monitor"))?;
            }
        }
        crate::validate::check_min_i64(self.seq_no, 0i64)
            .map_err(|error| error.in_field("seqNo"))?;
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyMonitoringReportRequest<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP: usize = 8usize,
    const MONITORING_DATA_VARIABLE_MONITORING_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub monitor: Option<
        heapless::Vec<
            MonitoringData<CustomDataType, MONITORING_DATA_VARIABLE_MONITORING_CAP>,
            NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP,
        >,
    >,
    /// The id of the GetMonitoringRequest that requested this report.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP: usize,
    const MONITORING_DATA_VARIABLE_MONITORING_CAP: usize,
> crate::Action
for NotifyMonitoringReportRequest<
    CustomDataType,
    NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP,
    MONITORING_DATA_VARIABLE_MONITORING_CAP,
> {
    const ACTION: &'static str = "NotifyMonitoringReport";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP: usize,
    const MONITORING_DATA_VARIABLE_MONITORING_CAP: usize,
> crate::validate::Validate
for NotifyMonitoringReportRequest<
    CustomDataType,
    NOTIFY_MONITORING_REPORT_REQUEST_MONITOR_CAP,
    MONITORING_DATA_VARIABLE_MONITORING_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.monitor {
            crate::validate::check_min_items(value.len(), 1usize)
                .map_err(|error| error.in_field("monitor"))?;
            for (index, item) in value.iter().enumerate() {
                crate::validate::Validate::validate(item)
                    .map_err(|error| error.in_index(index).in_field("monitor"))?;
            }
        }
        crate::validate::check_min_i64(self.seq_no, 0i64)
            .map_err(|error| error.in_field("seqNo"))?;
        Ok(())
    }
}
