// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifySettlementResponse {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The receipt id if the receipt is generated by CSMS.
    #[cfg_attr(feature = "serde", serde(rename = "receiptId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_id: Option<heapless::String<50usize>>,
    /// The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
    #[cfg_attr(feature = "serde", serde(rename = "receiptUrl"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_url: Option<heapless::String<2000usize>>,
}
impl crate::Action for NotifySettlementResponse {
    const ACTION: &'static str = "NotifySettlement";
}
