// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifySettlementRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The payment reference received from the payment terminal and is used as the value for _idToken_.
    #[cfg_attr(feature = "serde", serde(rename = "pspRef"))]
    pub psp_ref: heapless::String<255usize>,
    #[cfg_attr(feature = "serde", serde(rename = "receiptId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_id: Option<heapless::String<50usize>>,
    /// The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
    #[cfg_attr(feature = "serde", serde(rename = "receiptUrl"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_url: Option<alloc::string::String>,
    /// The amount that was settled, or attempted to be settled (in case of failure).
    #[cfg_attr(feature = "serde", serde(rename = "settlementAmount"))]
    pub settlement_amount: f64,
    /// The time when the settlement was done.
    #[cfg_attr(feature = "serde", serde(rename = "settlementTime"))]
    pub settlement_time: crate::OcppTimestamp,
    pub status: PaymentStatusEnum,
    /// Additional information from payment terminal/payment process.
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<heapless::String<500usize>>,
    /// The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_id: Option<heapless::String<36usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vatCompany"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_company: Option<Address<CustomDataType>>,
    /// VAT number for a company receipt.
    #[cfg_attr(feature = "serde", serde(rename = "vatNumber"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_number: Option<heapless::String<20usize>>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifySettlementRequest<CustomDataType> {
    const ACTION: &'static str = "NotifySettlement";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for NotifySettlementRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.receipt_url {
            crate::validate::check_max_length(value, 2000usize)
                .map_err(|error| error.in_field("receiptUrl"))?;
        }
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        if let Some(value) = &self.vat_company {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("vatCompany"))?;
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifySettlementRequest<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_SETTLEMENT_REQUEST_RECEIPT_URL_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The payment reference received from the payment terminal and is used as the value for _idToken_.
    #[cfg_attr(feature = "serde", serde(rename = "pspRef"))]
    pub psp_ref: heapless::String<255usize>,
    #[cfg_attr(feature = "serde", serde(rename = "receiptId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_id: Option<heapless::String<50usize>>,
    /// The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
    #[cfg_attr(feature = "serde", serde(rename = "receiptUrl"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub receipt_url: Option<heapless::String<NOTIFY_SETTLEMENT_REQUEST_RECEIPT_URL_CAP>>,
    /// The amount that was settled, or attempted to be settled (in case of failure).
    #[cfg_attr(feature = "serde", serde(rename = "settlementAmount"))]
    pub settlement_amount: f64,
    /// The time when the settlement was done.
    #[cfg_attr(feature = "serde", serde(rename = "settlementTime"))]
    pub settlement_time: crate::OcppTimestamp,
    pub status: PaymentStatusEnum,
    /// Additional information from payment terminal/payment process.
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<heapless::String<500usize>>,
    /// The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub transaction_id: Option<heapless::String<36usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "vatCompany"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_company: Option<Address<CustomDataType>>,
    /// VAT number for a company receipt.
    #[cfg_attr(feature = "serde", serde(rename = "vatNumber"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub vat_number: Option<heapless::String<20usize>>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_SETTLEMENT_REQUEST_RECEIPT_URL_CAP: usize,
> crate::Action
for NotifySettlementRequest<CustomDataType, NOTIFY_SETTLEMENT_REQUEST_RECEIPT_URL_CAP> {
    const ACTION: &'static str = "NotifySettlement";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const NOTIFY_SETTLEMENT_REQUEST_RECEIPT_URL_CAP: usize,
> crate::validate::Validate
for NotifySettlementRequest<CustomDataType, NOTIFY_SETTLEMENT_REQUEST_RECEIPT_URL_CAP> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        if let Some(value) = &self.receipt_url {
            crate::validate::check_max_length(value, 2000usize)
                .map_err(|error| error.in_field("receiptUrl"))?;
        }
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        if let Some(value) = &self.vat_company {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("vatCompany"))?;
        }
        Ok(())
    }
}
