// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyDERStartStopResponse<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
impl<CustomDataType> crate::Action for NotifyDERStartStopResponse<CustomDataType> {
    const ACTION: &'static str = "NotifyDERStartStop";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for NotifyDERStartStopResponse<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        Ok(())
    }
}
