// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyEventRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "eventData"))]
    pub event_data: alloc::vec::Vec<EventData<CustomDataType>>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: crate::OcppTimestamp,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the report follows in an upcoming notifyEventRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for NotifyEventRequest<CustomDataType> {
    const ACTION: &'static str = "NotifyEvent";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotifyEventRequest<
    CustomDataType = crate::NoCustomData,
    const NOTIFY_EVENT_REQUEST_EVENT_DATA_CAP: usize = 8usize,
    const EVENT_DATA_ACTUAL_VALUE_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "eventData"))]
    pub event_data: heapless::Vec<
        EventData<CustomDataType, EVENT_DATA_ACTUAL_VALUE_CAP>,
        NOTIFY_EVENT_REQUEST_EVENT_DATA_CAP,
    >,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "generatedAt"))]
    pub generated_at: crate::OcppTimestamp,
    /// Sequence number of this message. First message starts at 0.
    #[cfg_attr(feature = "serde", serde(rename = "seqNo"))]
    pub seq_no: i64,
    /// “to be continued” indicator. Indicates whether another part of the report follows in an upcoming notifyEventRequest message. Default value when omitted is false.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const NOTIFY_EVENT_REQUEST_EVENT_DATA_CAP: usize,
    const EVENT_DATA_ACTUAL_VALUE_CAP: usize,
> crate::Action
for NotifyEventRequest<
    CustomDataType,
    NOTIFY_EVENT_REQUEST_EVENT_DATA_CAP,
    EVENT_DATA_ACTUAL_VALUE_CAP,
> {
    const ACTION: &'static str = "NotifyEvent";
}
