// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReportChargingProfilesRequest {
    /// Source that has installed this charging profile. Values defined in Appendix as ChargingLimitSourceEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: heapless::String<20usize>,
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: alloc::vec::Vec<ChargingProfile>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The evse to which the charging profile applies. If evseId = 0, the message contains an overall limit for the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Id used to match the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt; message with the resulting ReportChargingProfilesRequest messages. When the CSMS provided a requestId in the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt;, this field SHALL contain the same value.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// To Be Continued. Default value when omitted: false. false indicates that there are no further messages as part of this report.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl crate::Action for ReportChargingProfilesRequest {
    const ACTION: &'static str = "ReportChargingProfiles";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReportChargingProfilesRequest<
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize = 16usize,
    const ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP: usize = 1024usize,
    const PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP: usize = 1024usize,
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize = 1024usize,
    const CHARGING_PROFILE_DYN_UPDATE_TIME_CAP: usize = 1024usize,
    const CHARGING_PROFILE_VALID_FROM_CAP: usize = 1024usize,
    const CHARGING_PROFILE_VALID_TO_CAP: usize = 1024usize,
> {
    /// Source that has installed this charging profile. Values defined in Appendix as ChargingLimitSourceEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: heapless::String<20usize>,
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: heapless::Vec<
        ChargingProfile<
            ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP,
            PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP,
            CHARGING_SCHEDULE_START_SCHEDULE_CAP,
            CHARGING_PROFILE_DYN_UPDATE_TIME_CAP,
            CHARGING_PROFILE_VALID_FROM_CAP,
            CHARGING_PROFILE_VALID_TO_CAP,
        >,
        REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The evse to which the charging profile applies. If evseId = 0, the message contains an overall limit for the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Id used to match the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt; message with the resulting ReportChargingProfilesRequest messages. When the CSMS provided a requestId in the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt;, this field SHALL contain the same value.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// To Be Continued. Default value when omitted: false. false indicates that there are no further messages as part of this report.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP: usize,
    const PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP: usize,
    const CHARGING_SCHEDULE_START_SCHEDULE_CAP: usize,
    const CHARGING_PROFILE_DYN_UPDATE_TIME_CAP: usize,
    const CHARGING_PROFILE_VALID_FROM_CAP: usize,
    const CHARGING_PROFILE_VALID_TO_CAP: usize,
> crate::Action
for ReportChargingProfilesRequest<
    REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    ABSOLUTE_PRICE_SCHEDULE_TIME_ANCHOR_CAP,
    PRICE_LEVEL_SCHEDULE_TIME_ANCHOR_CAP,
    CHARGING_SCHEDULE_START_SCHEDULE_CAP,
    CHARGING_PROFILE_DYN_UPDATE_TIME_CAP,
    CHARGING_PROFILE_VALID_FROM_CAP,
    CHARGING_PROFILE_VALID_TO_CAP,
> {
    const ACTION: &'static str = "ReportChargingProfiles";
}
