// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReportChargingProfilesRequest<CustomDataType = crate::NoCustomData> {
    /// Source that has installed this charging profile. Values defined in Appendix as ChargingLimitSourceEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: heapless::String<20usize>,
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: alloc::vec::Vec<ChargingProfile<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The evse to which the charging profile applies. If evseId = 0, the message contains an overall limit for the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Id used to match the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt; message with the resulting ReportChargingProfilesRequest messages. When the CSMS provided a requestId in the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt;, this field SHALL contain the same value.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// To Be Continued. Default value when omitted: false. false indicates that there are no further messages as part of this report.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for ReportChargingProfilesRequest<CustomDataType> {
    const ACTION: &'static str = "ReportChargingProfiles";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for ReportChargingProfilesRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.charging_profile.len(), 1usize)
            .map_err(|error| error.in_field("chargingProfile"))?;
        for (index, item) in self.charging_profile.iter().enumerate() {
            crate::validate::Validate::validate(item)
                .map_err(|error| error.in_index(index).in_field("chargingProfile"))?;
        }
        crate::validate::check_min_i64(self.evse_id, 0i64)
            .map_err(|error| error.in_field("evseId"))?;
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReportChargingProfilesRequest<
    CustomDataType = crate::NoCustomData,
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize = 8usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize = 1024usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize = 8usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize = 8usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize = 8usize,
> {
    /// Source that has installed this charging profile. Values defined in Appendix as ChargingLimitSourceEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "chargingLimitSource"))]
    pub charging_limit_source: heapless::String<20usize>,
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    pub charging_profile: heapless::Vec<
        ChargingProfile<
            CustomDataType,
            ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
            ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
            CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
            CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
            CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
            PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
            SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
        >,
        REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The evse to which the charging profile applies. If evseId = 0, the message contains an overall limit for the Charging Station.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// Id used to match the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt; message with the resulting ReportChargingProfilesRequest messages. When the CSMS provided a requestId in the &lt;&lt;getchargingprofilesrequest, GetChargingProfilesRequest&gt;&gt;, this field SHALL contain the same value.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// To Be Continued. Default value when omitted: false. false indicates that there are no further messages as part of this report.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub tbc: Option<bool>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
> crate::Action
for ReportChargingProfilesRequest<
    CustomDataType,
    REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
    PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
> {
    const ACTION: &'static str = "ReportChargingProfiles";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
> crate::validate::Validate
for ReportChargingProfilesRequest<
    CustomDataType,
    REPORT_CHARGING_PROFILES_REQUEST_CHARGING_PROFILE_CAP,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
    PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_items(self.charging_profile.len(), 1usize)
            .map_err(|error| error.in_field("chargingProfile"))?;
        for (index, item) in self.charging_profile.iter().enumerate() {
            crate::validate::Validate::validate(item)
                .map_err(|error| error.in_index(index).in_field("chargingProfile"))?;
        }
        crate::validate::check_min_i64(self.evse_id, 0i64)
            .map_err(|error| error.in_field("evseId"))?;
        Ok(())
    }
}
