// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RequestBatterySwapRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken,
    /// Request id to match with BatterySwapRequest.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(feature = "alloc")]
impl crate::Action for RequestBatterySwapRequest {
    const ACTION: &'static str = "RequestBatterySwap";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RequestBatterySwapRequest<
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize = 16usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken<ID_TOKEN_ADDITIONAL_INFO_CAP>,
    /// Request id to match with BatterySwapRequest.
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<const ID_TOKEN_ADDITIONAL_INFO_CAP: usize> crate::Action
for RequestBatterySwapRequest<ID_TOKEN_ADDITIONAL_INFO_CAP> {
    const ACTION: &'static str = "RequestBatterySwap";
}
