// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RequestStartTransactionRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_profile: Option<ChargingProfile<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// Number of the EVSE on which to start the transaction. EvseId SHALL be &gt; 0
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "groupIdToken"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub group_id_token: Option<IdToken<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken<CustomDataType>,
    /// Id given by the server to this start request. The Charging Station will return this in the &lt;&lt;transactioneventrequest, TransactionEventRequest&gt;&gt;, letting the server know which transaction was started for this request. Use to start a transaction.
    #[cfg_attr(feature = "serde", serde(rename = "remoteStartId"))]
    pub remote_start_id: i64,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for RequestStartTransactionRequest<CustomDataType> {
    const ACTION: &'static str = "RequestStartTransaction";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RequestStartTransactionRequest<
    CustomDataType = crate::NoCustomData,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize = 1024usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize = 8usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize = 8usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize = 8usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize = 8usize,
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfile"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub charging_profile: Option<
        ChargingProfile<
            CustomDataType,
            ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
            ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
            CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
            CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
            CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
            PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
            SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// Number of the EVSE on which to start the transaction. EvseId SHALL be &gt; 0
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
    #[cfg_attr(feature = "serde", serde(rename = "groupIdToken"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub group_id_token: Option<IdToken<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP>>,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP>,
    /// Id given by the server to this start request. The Charging Station will return this in the &lt;&lt;transactioneventrequest, TransactionEventRequest&gt;&gt;, letting the server know which transaction was started for this request. Use to start a transaction.
    #[cfg_attr(feature = "serde", serde(rename = "remoteStartId"))]
    pub remote_start_id: i64,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP: usize,
    const ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP: usize,
    const CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP: usize,
    const CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP: usize,
    const PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP: usize,
    const SALES_TARIFF_SALES_TARIFF_ENTRY_CAP: usize,
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize,
> crate::Action
for RequestStartTransactionRequest<
    CustomDataType,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_ALGORITHM_CAP,
    ABSOLUTE_PRICE_SCHEDULE_PRICE_RULE_STACKS_CAP,
    CHARGING_SCHEDULE_CHARGING_SCHEDULE_PERIOD_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_FREQ_WATT_CURVE_CAP,
    CHARGING_SCHEDULE_PERIOD_V2X_SIGNAL_WATT_CURVE_CAP,
    PRICE_LEVEL_SCHEDULE_PRICE_LEVEL_SCHEDULE_ENTRIES_CAP,
    SALES_TARIFF_SALES_TARIFF_ENTRY_CAP,
    ID_TOKEN_ADDITIONAL_INFO_CAP,
> {
    const ACTION: &'static str = "RequestStartTransaction";
}
