// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReserveNowRequest<CustomDataType = crate::NoCustomData> {
    /// This field specifies the connector type. Values defined in Appendix as ConnectorEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "connectorType"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_type: Option<heapless::String<20usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// This contains ID of the evse to be reserved.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
    /// Date and time at which the reservation expires.
    #[cfg_attr(feature = "serde", serde(rename = "expiryDateTime"))]
    pub expiry_date_time: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(rename = "groupIdToken"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub group_id_token: Option<IdToken<CustomDataType>>,
    /// Id of reservation.
    pub id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken<CustomDataType>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for ReserveNowRequest<CustomDataType> {
    const ACTION: &'static str = "ReserveNow";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReserveNowRequest<
    CustomDataType = crate::NoCustomData,
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize = 8usize,
> {
    /// This field specifies the connector type. Values defined in Appendix as ConnectorEnumStringType.
    #[cfg_attr(feature = "serde", serde(rename = "connectorType"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub connector_type: Option<heapless::String<20usize>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// This contains ID of the evse to be reserved.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub evse_id: Option<i64>,
    /// Date and time at which the reservation expires.
    #[cfg_attr(feature = "serde", serde(rename = "expiryDateTime"))]
    pub expiry_date_time: crate::OcppTimestamp,
    #[cfg_attr(feature = "serde", serde(rename = "groupIdToken"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub group_id_token: Option<IdToken<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP>>,
    /// Id of reservation.
    pub id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "idToken"))]
    pub id_token: IdToken<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP>,
}
#[cfg(not(feature = "alloc"))]
impl<CustomDataType, const ID_TOKEN_ADDITIONAL_INFO_CAP: usize> crate::Action
for ReserveNowRequest<CustomDataType, ID_TOKEN_ADDITIONAL_INFO_CAP> {
    const ACTION: &'static str = "ReserveNow";
}
