// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendLocalListResponse<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    pub status: SendLocalListStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<StatusInfo<CustomDataType>>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for SendLocalListResponse<CustomDataType> {
    const ACTION: &'static str = "SendLocalList";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for SendLocalListResponse<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        if let Some(value) = &self.status_info {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("statusInfo"))?;
        }
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendLocalListResponse<
    CustomDataType = crate::NoCustomData,
    const STATUS_INFO_ADDITIONAL_INFO_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    pub status: SendLocalListStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<StatusInfo<CustomDataType, STATUS_INFO_ADDITIONAL_INFO_CAP>>,
}
#[cfg(not(feature = "alloc"))]
impl<CustomDataType, const STATUS_INFO_ADDITIONAL_INFO_CAP: usize> crate::Action
for SendLocalListResponse<CustomDataType, STATUS_INFO_ADDITIONAL_INFO_CAP> {
    const ACTION: &'static str = "SendLocalList";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const STATUS_INFO_ADDITIONAL_INFO_CAP: usize,
> crate::validate::Validate
for SendLocalListResponse<CustomDataType, STATUS_INFO_ADDITIONAL_INFO_CAP> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        if let Some(value) = &self.status_info {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("statusInfo"))?;
        }
        Ok(())
    }
}
