// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendLocalListRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "localAuthorizationList"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub local_authorization_list: Option<
        alloc::vec::Vec<AuthorizationData<CustomDataType>>,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "updateType"))]
    pub update_type: UpdateEnum,
    /// In case of a full update this is the version number of the full list. In case of a differential update it is the version number of the list after the update has been applied.
    #[cfg_attr(feature = "serde", serde(rename = "versionNumber"))]
    pub version_number: i64,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for SendLocalListRequest<CustomDataType> {
    const ACTION: &'static str = "SendLocalList";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendLocalListRequest<
    CustomDataType = crate::NoCustomData,
    const SEND_LOCAL_LIST_REQUEST_LOCAL_AUTHORIZATION_LIST_CAP: usize = 8usize,
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize = 8usize,
    const ID_TOKEN_INFO_EVSE_ID_CAP: usize = 8usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "localAuthorizationList"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub local_authorization_list: Option<
        heapless::Vec<
            AuthorizationData<
                CustomDataType,
                ID_TOKEN_ADDITIONAL_INFO_CAP,
                ID_TOKEN_INFO_EVSE_ID_CAP,
                MESSAGE_CONTENT_CONTENT_CAP,
            >,
            SEND_LOCAL_LIST_REQUEST_LOCAL_AUTHORIZATION_LIST_CAP,
        >,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "updateType"))]
    pub update_type: UpdateEnum,
    /// In case of a full update this is the version number of the full list. In case of a differential update it is the version number of the list after the update has been applied.
    #[cfg_attr(feature = "serde", serde(rename = "versionNumber"))]
    pub version_number: i64,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const SEND_LOCAL_LIST_REQUEST_LOCAL_AUTHORIZATION_LIST_CAP: usize,
    const ID_TOKEN_ADDITIONAL_INFO_CAP: usize,
    const ID_TOKEN_INFO_EVSE_ID_CAP: usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize,
> crate::Action
for SendLocalListRequest<
    CustomDataType,
    SEND_LOCAL_LIST_REQUEST_LOCAL_AUTHORIZATION_LIST_CAP,
    ID_TOKEN_ADDITIONAL_INFO_CAP,
    ID_TOKEN_INFO_EVSE_ID_CAP,
    MESSAGE_CONTENT_CONTENT_CAP,
> {
    const ACTION: &'static str = "SendLocalList";
}
