// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetDERControlRequest<CustomDataType = crate::NoCustomData> {
    /// Unique id of this control, e.g. UUID
    #[cfg_attr(feature = "serde", serde(rename = "controlId"))]
    pub control_id: heapless::String<36usize>,
    #[cfg_attr(feature = "serde", serde(rename = "controlType"))]
    pub control_type: DERControlEnum,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub curve: Option<DERCurve<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "enterService"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub enter_service: Option<EnterService<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "fixedPFAbsorb"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub fixed_p_f_absorb: Option<FixedPF<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "fixedPFInject"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub fixed_p_f_inject: Option<FixedPF<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "fixedVar"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub fixed_var: Option<FixedVar<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(rename = "freqDroop"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub freq_droop: Option<FreqDroop<CustomDataType>>,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub gradient: Option<Gradient<CustomDataType>>,
    /// True if this is a default DER control
    #[cfg_attr(feature = "serde", serde(rename = "isDefault"))]
    pub is_default: bool,
    #[cfg_attr(feature = "serde", serde(rename = "limitMaxDischarge"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub limit_max_discharge: Option<LimitMaxDischarge<CustomDataType>>,
}
impl<CustomDataType> crate::Action for SetDERControlRequest<CustomDataType> {
    const ACTION: &'static str = "SetDERControl";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate for SetDERControlRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.control_type)
            .map_err(|error| error.in_field("controlType"))?;
        if let Some(value) = &self.curve {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("curve"))?;
        }
        if let Some(value) = &self.enter_service {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("enterService"))?;
        }
        if let Some(value) = &self.fixed_p_f_absorb {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("fixedPFAbsorb"))?;
        }
        if let Some(value) = &self.fixed_p_f_inject {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("fixedPFInject"))?;
        }
        if let Some(value) = &self.fixed_var {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("fixedVar"))?;
        }
        if let Some(value) = &self.freq_droop {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("freqDroop"))?;
        }
        if let Some(value) = &self.gradient {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("gradient"))?;
        }
        if let Some(value) = &self.limit_max_discharge {
            crate::validate::Validate::validate(value)
                .map_err(|error| error.in_field("limitMaxDischarge"))?;
        }
        Ok(())
    }
}
