// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetNetworkProfileRequest<CustomDataType = crate::NoCustomData> {
    /// Slot in which the configuration should be stored.
    #[cfg_attr(feature = "serde", serde(rename = "configurationSlot"))]
    pub configuration_slot: i64,
    #[cfg_attr(feature = "serde", serde(rename = "connectionData"))]
    pub connection_data: NetworkConnectionProfile<CustomDataType>,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for SetNetworkProfileRequest<CustomDataType> {
    const ACTION: &'static str = "SetNetworkProfile";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetNetworkProfileRequest<
    CustomDataType = crate::NoCustomData,
    const A_P_N_APN_CAP: usize = 1024usize,
    const NETWORK_CONNECTION_PROFILE_OCPP_CSMS_URL_CAP: usize = 1024usize,
    const V_P_N_SERVER_CAP: usize = 1024usize,
> {
    /// Slot in which the configuration should be stored.
    #[cfg_attr(feature = "serde", serde(rename = "configurationSlot"))]
    pub configuration_slot: i64,
    #[cfg_attr(feature = "serde", serde(rename = "connectionData"))]
    pub connection_data: NetworkConnectionProfile<
        CustomDataType,
        A_P_N_APN_CAP,
        NETWORK_CONNECTION_PROFILE_OCPP_CSMS_URL_CAP,
        V_P_N_SERVER_CAP,
    >,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const A_P_N_APN_CAP: usize,
    const NETWORK_CONNECTION_PROFILE_OCPP_CSMS_URL_CAP: usize,
    const V_P_N_SERVER_CAP: usize,
> crate::Action
for SetNetworkProfileRequest<
    CustomDataType,
    A_P_N_APN_CAP,
    NETWORK_CONNECTION_PROFILE_OCPP_CSMS_URL_CAP,
    V_P_N_SERVER_CAP,
> {
    const ACTION: &'static str = "SetNetworkProfile";
}
