// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetDefaultTariffRequest<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// EVSE that tariff applies to. When _evseId_ = 0, then tarriff applies to all EVSEs.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    pub tariff: Tariff<CustomDataType>,
}
#[cfg(feature = "alloc")]
impl<CustomDataType> crate::Action for SetDefaultTariffRequest<CustomDataType> {
    const ACTION: &'static str = "SetDefaultTariff";
}
#[cfg(all(feature = "validate", feature = "alloc"))]
impl<CustomDataType> crate::validate::Validate
for SetDefaultTariffRequest<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_i64(self.evse_id, 0i64)
            .map_err(|error| error.in_field("evseId"))?;
        crate::validate::Validate::validate(&self.tariff)
            .map_err(|error| error.in_field("tariff"))?;
        Ok(())
    }
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetDefaultTariffRequest<
    CustomDataType = crate::NoCustomData,
    const TARIFF_TIME_PRICES_CAP: usize = 8usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize = 1024usize,
    const TARIFF_ENERGY_PRICES_CAP: usize = 8usize,
    const TARIFF_FIXED_PRICES_CAP: usize = 8usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// EVSE that tariff applies to. When _evseId_ = 0, then tarriff applies to all EVSEs.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    pub tariff: Tariff<
        CustomDataType,
        TARIFF_TIME_PRICES_CAP,
        MESSAGE_CONTENT_CONTENT_CAP,
        TARIFF_ENERGY_PRICES_CAP,
        TARIFF_FIXED_PRICES_CAP,
    >,
}
#[cfg(not(feature = "alloc"))]
impl<
    CustomDataType,
    const TARIFF_TIME_PRICES_CAP: usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize,
    const TARIFF_ENERGY_PRICES_CAP: usize,
    const TARIFF_FIXED_PRICES_CAP: usize,
> crate::Action
for SetDefaultTariffRequest<
    CustomDataType,
    TARIFF_TIME_PRICES_CAP,
    MESSAGE_CONTENT_CONTENT_CAP,
    TARIFF_ENERGY_PRICES_CAP,
    TARIFF_FIXED_PRICES_CAP,
> {
    const ACTION: &'static str = "SetDefaultTariff";
}
#[cfg(all(feature = "validate", not(feature = "alloc")))]
impl<
    CustomDataType,
    const TARIFF_TIME_PRICES_CAP: usize,
    const MESSAGE_CONTENT_CONTENT_CAP: usize,
    const TARIFF_ENERGY_PRICES_CAP: usize,
    const TARIFF_FIXED_PRICES_CAP: usize,
> crate::validate::Validate
for SetDefaultTariffRequest<
    CustomDataType,
    TARIFF_TIME_PRICES_CAP,
    MESSAGE_CONTENT_CONTENT_CAP,
    TARIFF_ENERGY_PRICES_CAP,
    TARIFF_FIXED_PRICES_CAP,
> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::check_min_i64(self.evse_id, 0i64)
            .map_err(|error| error.in_field("evseId"))?;
        crate::validate::Validate::validate(&self.tariff)
            .map_err(|error| error.in_field("tariff"))?;
        Ok(())
    }
}
