// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetDERControlResponse {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    pub status: DERControlStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "statusInfo"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub status_info: Option<StatusInfo>,
    /// List of controlIds that are superseded as a result of setting this control.
    #[cfg_attr(feature = "serde", serde(rename = "supersededIds"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub superseded_ids: Option<heapless::Vec<heapless::String<36usize>, 24usize>>,
}
impl crate::Action for SetDERControlResponse {
    const ACTION: &'static str = "SetDERControl";
}
