// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct StatusNotificationRequest<CustomDataType = crate::NoCustomData> {
    /// The id of the connector within the EVSE for which the status is reported.
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    pub connector_id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "connectorStatus"))]
    pub connector_status: ConnectorStatusEnum,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    /// The id of the EVSE to which the connector belongs for which the the status is reported.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
    /// The time for which the status is reported.
    pub timestamp: crate::OcppTimestamp,
}
impl<CustomDataType> crate::Action for StatusNotificationRequest<CustomDataType> {
    const ACTION: &'static str = "StatusNotification";
}
