// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UnlockConnectorRequest {
    /// This contains the identifier of the connector that needs to be unlocked.
    #[cfg_attr(feature = "serde", serde(rename = "connectorId"))]
    pub connector_id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// This contains the identifier of the EVSE for which a connector needs to be unlocked.
    #[cfg_attr(feature = "serde", serde(rename = "evseId"))]
    pub evse_id: i64,
}
impl crate::Action for UnlockConnectorRequest {
    const ACTION: &'static str = "UnlockConnector";
}
