// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UnpublishFirmwareResponse<CustomDataType = crate::NoCustomData> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomDataType>,
    pub status: UnpublishFirmwareStatusEnum,
}
impl<CustomDataType> crate::Action for UnpublishFirmwareResponse<CustomDataType> {
    const ACTION: &'static str = "UnpublishFirmware";
}
#[cfg(feature = "validate")]
impl<CustomDataType> crate::validate::Validate
for UnpublishFirmwareResponse<CustomDataType> {
    fn validate(&self) -> Result<(), crate::validate::ValidationError> {
        crate::validate::Validate::validate(&self.status)
            .map_err(|error| error.in_field("status"))?;
        Ok(())
    }
}
