// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
/// Id of dynamic charging profile to update.
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateDynamicScheduleRequest {
    /// Id of charging profile to update.
    #[cfg_attr(feature = "serde", serde(rename = "chargingProfileId"))]
    pub charging_profile_id: i64,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    #[cfg_attr(feature = "serde", serde(rename = "scheduleUpdate"))]
    pub schedule_update: ChargingScheduleUpdate,
}
impl crate::Action for UpdateDynamicScheduleRequest {
    const ACTION: &'static str = "UpdateDynamicSchedule";
}
