// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[cfg(feature = "alloc")]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateFirmwareRequest {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    pub firmware: Firmware,
    /// The Id of this request
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// This specifies how many times Charging Station must retry to download the firmware before giving up. If this field is not present, it is left to Charging Station to decide how many times it wants to retry.
    /// If the value is 0, it means: no retries.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub retries: Option<i64>,
    /// The interval in seconds after which a retry may be attempted. If this field is not present, it is left to Charging Station to decide how long to wait between attempts.
    #[cfg_attr(feature = "serde", serde(rename = "retryInterval"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub retry_interval: Option<i64>,
}
#[cfg(feature = "alloc")]
impl crate::Action for UpdateFirmwareRequest {
    const ACTION: &'static str = "UpdateFirmware";
}
#[cfg(not(feature = "alloc"))]
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateFirmwareRequest<
    const FIRMWARE_INSTALL_DATE_TIME_CAP: usize = 1024usize,
    const FIRMWARE_RETRIEVE_DATE_TIME_CAP: usize = 1024usize,
> {
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    pub firmware: Firmware<
        FIRMWARE_INSTALL_DATE_TIME_CAP,
        FIRMWARE_RETRIEVE_DATE_TIME_CAP,
    >,
    /// The Id of this request
    #[cfg_attr(feature = "serde", serde(rename = "requestId"))]
    pub request_id: i64,
    /// This specifies how many times Charging Station must retry to download the firmware before giving up. If this field is not present, it is left to Charging Station to decide how many times it wants to retry.
    /// If the value is 0, it means: no retries.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub retries: Option<i64>,
    /// The interval in seconds after which a retry may be attempted. If this field is not present, it is left to Charging Station to decide how long to wait between attempts.
    #[cfg_attr(feature = "serde", serde(rename = "retryInterval"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub retry_interval: Option<i64>,
}
#[cfg(not(feature = "alloc"))]
impl<
    const FIRMWARE_INSTALL_DATE_TIME_CAP: usize,
    const FIRMWARE_RETRIEVE_DATE_TIME_CAP: usize,
> crate::Action
for UpdateFirmwareRequest<
    FIRMWARE_INSTALL_DATE_TIME_CAP,
    FIRMWARE_RETRIEVE_DATE_TIME_CAP,
> {
    const ACTION: &'static str = "UpdateFirmware";
}
