// @generated by ocpp-codegen from schemas/. Do not edit by hand -- run
// `scripts/generate.sh` to regenerate; manual changes will be overwritten.

use super::common::*;
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UsePriorityChargingRequest {
    /// True to request priority charging.
    /// False to request stopping priority charging.
    pub activate: bool,
    #[cfg_attr(feature = "serde", serde(rename = "customData"))]
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub custom_data: Option<CustomData>,
    /// The transaction for which priority charging is requested.
    #[cfg_attr(feature = "serde", serde(rename = "transactionId"))]
    pub transaction_id: heapless::String<36usize>,
}
impl crate::Action for UsePriorityChargingRequest {
    const ACTION: &'static str = "UsePriorityCharging";
}
